### ISSUE TITLE
Reconsider 1600 play out instead of 3200Visit?

### ISSUE THREAD

**Issue by thynson** [leela-zero/leela-zero#1012]
Recently leelaz is looks like to stall again, which seems too early than 5 block and 6block. 
I'm in doubt if fixed playout is better than fixed visit count. 

We all know that as subtree is reused, leelaz will quickly response to a forced move under fixed visit count configuration. This could make leelaz less likely to to consider other candidates, even if noise is added here. Imagine that when leelaz reponse to a forced move and 1601 visit is reused in the subtree, now the dirichelet noise is luckly to point out a better move, even if it increase the winning rate to 100%, due to fixed 3200 visit count, it get no more than 1599 visit eventually, and leelaz won't choose it unless it happens before 30 moves. 

Fixed visit anyhow weaken the effect of the noise. With fixed visit setting, leelaz plays like a stubborn human that sticks to known knowledges. While one should be more flexible when learning new things.  

However when doing match between two networks, fixed visit is still better than fixed playout.

**Comment by yenw** [comment]
Reconsider 3200 play out instead of 3200Visit?

**Comment by thynson** [comment]
@yenw I think the problem is we should use fixed playout, not 1600 or 3200.

**Comment by jkiliani** [comment]
I don't think the stall can be attributed to the change to -v with any degree of confidence, and in any case we had far longer stalls than this while using -p. To change back would require a lot more compelling argument with actual evidence. Since the Minigo project investigated the influence of tree reuse on Dirichlet noise efficiency and found no adverse effects (and this is what this issue is about basically), why should we disregard their findings and change back to a less efficient search just because of a hunch?

**Comment by thynson** [comment]
The previous longs stall could be subject to capacity of the network, while this time it could be not. And I'm not argue whether tree should be reused, and AlphaGo seems did reuse if I rembember correctly, I'm argue that fixed visit count could disable the noise effect after a forced move.
> Imagine that when leelaz reponse to a forced move and 1601 visit is reused in the subtree, now the dirichelet noise is luckly to point out a better move, even if it increase the winning rate to 100%, due to fixed 3200 visit count, it get no more than 1599 visit eventually, and leelaz won't choose it unless it happens before 30 moves.

Note that leelaz select best node with most visit count in UCT search, if leelaz believe it's forced move and more than 1600 visit is reused we are wasting power to search other possible move actually, I repeat again here, since any other candicate move will get visit count **no more than 1600**

**Comment by jkiliani** [comment]
I have a different proposal that would address this issue, in form of a two part solution: One, implement a cap on tree reuse at a reasonable level, e.g. 90%. This should mean that at 3200 visits, if the player to move already has 3050 visits due to tree reuse, there should be an overshoot to the visit count so at least 10% of visits, i.e. 320, are actual playouts for the player to move. Second, the mixing factor of policy priors to Dirichlet noise should no longer be static at 75% to 25%, but variable based on the level of tree reuse. In the case of capped reuse, the search at root level should be 100% Dirichlet noise, at lower but still high reuse levels, the mixing should still be scaled up in some way to get Dirichlet noise playouts better represented in the final training data. As long as a better move is found and gets a decent number of visits, it does not really matter if that move is not selected this time, as long as it makes it into the training data.

**Comment by jkiliani** [comment]
> Note that leelaz select best node with most visit count in UCT search, if leelaz believe it's forced move and more than 1600 visit is reused we are wasting power to search other possible move actually, I repeat again here, since any other candicate move will get visit count no more than 1600

This is simply incorrect for training games. The training output will see the correct move even if it wasn't selected as best candidate move, and future networks trained on this game will have their policy priors adjusted to search the correct move in a similar situation in the first place. There's a reason we don't use time management code in training games.

**Comment by Eddh** [comment]
We can also just increase number of visits from 3200 to 4000 or more since it seems like 3200 might be too low.

**Comment by thynson** [comment]
>Note that leelaz select best node with most visit count in UCT search
If we adopt overshoot approach, overshoot need to be at least greater than (2*ReusedVisit - MaxVisit), otherwise no other possible candidate could be select. But if we choose (2*ReusedVisit - MaxVisit) overshoot, in a very long forced branch, it lead to exponential explosion.

The second approach didn't not change the situation anyway. Please reconsier:
1. We limit visit count to 3200 visit selfplay, search tree is shared by white and black
2. Force move usually lead to 90% reused
3. Black spend 2000 visit on a force move and in that branch there is one node with 1601 visit
4. Black play such move, white reused 1601 visit
5. White has no other choice even if it found a better move, it could have 1599 visit at most

**Comment by thynson** [comment]
@Eddh Change 3200 to 4000 fixes nothing. See my last comment and change 1601 to 2001.

**Comment by Eddh** [comment]
Hmm so the point is that --visits reduce effectiveness of Dirichlet noise more than --playouts, and that it doesn't search more even when the move is actually not forced at all because the preceding move was forced and thus all visits were reused ?
Maybe instead of stopping when the total visit count hit -v value we could stop when the top visited move hit -v value.

**Comment by thynson** [comment]
@Eddh That sounds more reasonable than fixed visit count, but why not just fixed play out? Your proposal could lead to other problem while fixed playout is used by AlphaGo Zero.

**Comment by Eddh** [comment]
https://github.com/gcp/leela-zero/pull/590 fixed visits apparently was an elo improvement with same cpu usage over fixed playout.

**Comment by thynson** [comment]
@Eddh So it could be used in match, but not selfplay

**Comment by jkiliani** [comment]
I still think capping tree reuse and scaling up Dirichlet noise compared to policy priors at high reuse would work, even more effectively than fixed playouts. Expecting a move found by noise to potentially beat the most visited variant in playouts is an unreasonable requirement, and unnecessary too. The move found by Dirichlet noise only needs to make it into the training data with enough visits that future nets will find it in time.

**Comment by thynson** [comment]
@jkiliani No data support but I believe that lead to lower training quality and need more game to boost same ELO for a new weight. Fixed visit count boost a single game, but could increase the cost (ELO/game) of new weight.

**Comment by Marcin1960** [comment]
@jkiliani "Expecting a move found by noise to potentially beat the most visited variant in playouts is an unreasonable requirement, and unnecessary too. "

At certain level of perfection of complicated systems, random mutations are nor profitable. More efficient is shuffling of already existing  smart genetic structures.

**Comment by hydrogenpi** [comment]
THis is not good at all. 10 blocks is stalling faster than air france 447 in a storm

**Comment by jkiliani** [comment]
It's a bit early to call it that. We had a very high game rate those last two days, and not that many tested networks. Also, we probably can't expect 10x128 to gain as much over 6x128 as 6x128 gained compared to 5x64, since there was the shuffle buffer fix providing a huge boost, and FPU reduction another minor one.

I still expect 10 blocks to continue for quite a bit.

**Comment by gcp** [comment]
10 blocks was a minuscule size increase (60%) compared to last ones (480%), and immediately got a huge strength jump, so I'm not sure what you expect. Please keep random speculation and conclusions based on sample size = 1 out of this project. They will only lead me to completely and utterly ignore everything that you are saying even if you have a valid point.

If the thing raised in this thread would be a concern, it seems more logical to just use Dirichlet noise everywhere.

**Comment by jkiliani** [comment]
Interesting idea, using Dirichlet noise not just at the root but everywhere. Has this ever been tried?

**Comment by gcp** [comment]
Not that I know of. I would expect it to make the engine weaker. But it is more consistent to not treat the root specifically. (For the "randomized selection" this does not really apply because we only have to pick a move to play at the root)

The argument in this thread that on a forced sequence there is no possibility to inject noise seems correct, though I do wonder: is it really possible that we play moves instantly before giving the noised move the opportunity to get some playouts? After all, we stopped the search of the previous move already when *that* got 3200 visits at its root, so it would require the policy prior for the move played to be basically 100% *at the root*, *despite noise*.

There is no need to actually play the move to find that it's better, as long as it can accumulate some playouts (which raises the prior next time). Visits versus playouts doesn't make any difference at all here as with playouts the move has to overcome the accumulated playouts from before!

So I'm not convinced there's even an issue at all here.

**Comment by thynson** [comment]
@gcp Well, I do support that noise should be added when children are created if tree is reused, through I don't know why AlphaGo Zero didn't go this way. Maybe they concerned about it affects the accuracy of  wining rate.

**Comment by gcp** [comment]
>Well, I do support that noise should be added when children are created if tree is reused

We already do this, but it's unrelated to the issue raised in this thread.

**Comment by gcp** [comment]
>Maybe they concerned about it affects the accuracy of wining rate.

I don't understand. That is provided by the value network and the search. The policy network only guides the search "what to look at".

**Comment by thynson** [comment]
> We already do this, but it's unrelated to the issue raised in this thread.
Sorry, but isn't `UCTNode::dirichlet_noise()` only be called from `UCTSearch::think` for root node?

**Comment by thynson** [comment]
> I don't understand. That is provided by the value network and the search. The policy network only guides the search "what to look at".
As noise affect search, the wining rate may be inaccurate when visit count is low, which is recorded for training if I understand correctly.

**Comment by jkiliani** [comment]
I would also expect that using noise on every node weakens the engine a bit, but it may well be a net gain for training. For instance, injecting noise on depth 2 nodes would allow the engine to sometimes find unexpected refutations for moves it considers. It may not be easy to find any optimal solutions for the interaction of noise with tree reuse, but some sort of scaling where noise is used normally at root and at reduced levels further up the search tree may be worth considering.

It seems Leela Chess is for the moment going to have the NN cache implemented but no tree reuse, mainly for this exact issue (and they urgently need the noise at the moment to fix the abysmal policy priors...)

**Comment by gcp** [comment]
>which is recorded for training if I understand correctly.

No, it's not.

**Comment by gcp** [comment]
>Sorry, but isn't UCTNode::dirichlet_noise() only be called from UCTSearch::think for root node?

Yes. You said "when children are created if the tree is reused". If the tree is reused children don't need to be created, but we still explicitly re-noise the root.

**Comment by thynson** [comment]
So what I mean is add noise to the score at the time children is created, rather than wait till it become root node.

**Comment by gcp** [comment]
>Sorry, but isn't UCTNode::dirichlet_noise() only be called from UCTSearch::think for root node?

Yes. You said "when children are created if the tree is reused". If the tree is reused children don't need to be created, but we still explicitly re-noise the root.

**Comment by thynson** [comment]
Okay, anyway dirichlet noise is a bit out of topic here.
And I still vote for fixed playout. This issue could be closed if there is no room for discussion.

**Comment by gcp** [comment]
I think it was an interesting thing to bring up but because of the analysis above https://github.com/gcp/leela-zero/issues/1012#issuecomment-372247470 I am not convinced there is much practical difference here between visits and playouts. It's very hard to "discover" new things if there is a single move with a huge policy prior (which is what a forced sequence is) for both playouts and visits. It might be good to look at some actual cases to get some better idea of how substantial the difference is.

It is true that Dirichlet noise is rather ineffective in forced sequences for both systems. This is why noising everywhere might be worth consideration, but it is problematic to test. (Unless, perhaps, we are stalled at 256x20 :-)

**Comment by jkiliani** [comment]
How difficult would it be to measure the strength loss from noising everywhere? That could be the basis of a discussion, along with actual cases.

**Comment by killerducky** [comment]
If anyone is willing to do some experiments, I propose this: 

1) Run a selfplay game with `-l orig.txt`, at the end save the sgf `printsgf orig.sgf`
2) Turn off tree reuse completely, leave noise on, use `-l noreuse.txt`, iterate through every position of orig.sgf `loadsgf orig.sgf 1` `go`, repeat for every move. 
3) Compare orig.txt and noreuse.txt to see how different it is.
4) Turn off tree reuse completely for self play games and measure how much slower it is. I suspect due to NNCache it will not be very much slower. 

Then we can decide based on evidence in 3 and 4 if it's worth turning of tree reuse. 

I think this is promising, if no one else does this I might have time next weekend to try it. I hope more people will pitch in with doing experiments, they are very time consuming.

**Comment by gcp** [comment]
>How difficult would it be to measure the strength loss from noising everywhere? That could be the basis of a discussion, along with actual cases.

Just a simple validation or gomill run.

**Comment by gcp** [comment]
>Turn off tree reuse completely for self play games and measure how much slower it is. I suspect due to NNCache it will not be very much slower.

This is problematic with fixed playouts or visits?

**Comment by Eddh** [comment]
Isn't it too late to go back to more exploration ? Normally with an annealing process you start with exploration and then converge. We've converged quite far already. The "noise everywhere" technique might work if you do it from the beginning but not now. It could make us get out of the local optima but the nets produced might be worse, and since we are not using AZ technique of always promote, no new net would get promoted.

**Comment by gcp** [comment]
By this reasoning it would have made sense to anneal the noise amplitude rather than have it constant, FWIW.

The noise technique seems more like an adversarial trick to me, rather than part of an annealing process. The MCTS training setup with learning the probabilities means that as soon as you discover something, and it seems not noticeably better than what you had, it can "grow" as each training pass will increase the MCTS prior until it can overtake the best move.

The promotions don't seem like a problem for me, as all nets will suffer from the "noise" equally. It's the same for the current noise and "randomized first 30 moves".

**Comment by Eddh** [comment]
When getting out of a local optimum, you need to go uphill first. That's why nets that are trained on full noised tree might be worse at first. It could be better in the long run if there is a better optima elsewhere, but these worse nets would not be promoted and we would be locked in place.

I agree that the noise technique is more than part of an annealing process, but I think it does have an effect similar to noise in an annealing process. If you imagine turning up randomness to the max on every move, flooding the policy priors and leading to a lot of wtf moves (though guided by the VN), would the nets trained from it be as good ?

By the way what you describe, noise allowing you to consider seemingly bad moves, just seems like an annealing process to me. Discovering a potentially better region of the search space is exactly what noise is for in a annealing process. You can see it in action here for example https://www.youtube.com/watch?v=iaq_Fpr4KZc. the noise make it climb out of the local optimum just enough to end up finding the global optimum. The problem in our context is that the promotion system just wouldn't allow us to climb up.

This AGZ algorithm works differently though in that, the reducing of noise seems to come from the nets becoming more opinionated about what moves are good, thus snuffing out the noise thanks to 90% policy on just 1 move, whereas when it doesn't know what to do, the noise's effect will be felt more. So maybe in this context reducing the noise overtime is redundant.

Anyway I'm not against trying, but then if it fails, we wouldn't really know if the technique itself is bad, or if it's just that it was not the right time to try it, or that we needed the always promote technique to use it.

**Comment by gcp** [comment]
>seems like an annealing process to me

This would imply the procedure gradually lowers it, but that's not the case.

>I think it works differently though in that, in the AGZ pipeline, the reducing of noise seems to come from the nets becoming more opinionated about what moves are good, thus snuffing out the noise thanks to 90% policy on just 1 move, whereas when it doesn't know what to do, the noise's effect will be felt more. So maybe in this context reducing the noise over time is redundant.

No, I don't believe this is not how it works at all. If the net discovers a better move thanks to the noise, it will *increase* in probability each iteration, not get "snuffed out". This kind of reversal has been very visible with 4-4 vs 4-3 and 3-3.

I said that the shape of the Dirichlet noise is relevant here, because it can be extremely peaky, which works against anything that resembles averaging.

**Comment by gcp** [comment]
I did a run with -v 3200 -m 30 -n and -o 1600 -m 30 -n for the other topic, and the logfile is interesting:

```
B17 ->    3199 (V: 46.04%) (N: 74.79%) PV: B17 D16 B16 O16 G15 G16 J15 E5 C4 K3 H16 H14 H15 F14
 P14 ->       0 (V:  0.00%) (N:  0.17%) PV: P14 
10.6 average depth, 20 max depth
2309 non leaf nodes, 1.39 average children
3200 visits, 1009698 nodes, 1570 playouts, 530 n/s
```

```
 D16 ->    4434 (V: 54.27%) (N: 74.52%) PV: D16 B16 O16 G15 G16 J15 E5 D5 E3 D4 J3 H16 H14 H15 F14 G3 M3
 B16 ->       0 (V:  0.00%) (N:  0.40%) PV: B16 
10.1 average depth, 22 max depth
3204 non leaf nodes, 1.38 average children
4435 visits, 1396901 nodes, 1600 playouts, 489 n/s
```

I thought that the playouts version would get a better chance to explore the low policy entries because it's guaranteed to add playouts at every node in a forced variation, but in practice it seems that it mostly just ends up adding playouts to the already highest policy move.

What actually happens is the following: at the "start" of a forced variation, the visits version has a better chance to pick up a (noised) low policy move and avoid the variation in the first place, because it has more overall visits at that point. At the "end" of a forced variation, the playouts versions has a better chance to find a low policy move because it can accumulate a ton of playouts along the way.

You can also see how the "epsilon" of 0.25 approximately caps the maximum policy score of any move to 75%, but unless some other move is a bit lucky to get a lot of the noise, that isn't enough to explore other moves along the line most of the time. But sometimes it does:

``
  B8 ->    3193 (V: 53.75%) (N: 72.87%) PV: B8 B7 B6 B9 A7 C10 G11 K13 J12 J11 K14 H12 H13 G12 F12 H11 F11 D9 H17 M13
 Q10 B13 B14 B19 A15
 G11 ->       3 (V: 43.87%) (N:  0.79%) PV: G11 B8 F10
 F12 ->       3 (V: 43.63%) (N:  0.89%) PV: F12 B8 F10
11.7 average depth, 26 max depth
2196 non leaf nodes, 1.46 average children
3200 visits, 835702 nodes, 1753 playouts, 520 n/s
```

**Comment by barrtgt** [comment]
I think not having dirichlet noise for the "forced" moves is a mistake. It will make it more difficult or even impossible to find good moves with a low policy in these areas. We know the network has to be reminded of how to do endgame and count by forcing it with resignation disabled. And we know the network can get some evaluations very wrong. Without the noise, how can it verify these moves are forced? If you really like the speed up using visits provides, can you at least have it play out these moves as if it were playouts 10% of the time?

**Comment by jkiliani** [comment]
I just studied the effectiveness of Dirichlet noise in the context of implementing FPU reduction for Leela Chess here: https://github.com/glinscott/leela-chess/issues/160#issuecomment-375090149. It looks like it might be a good idea to disable FPU reduction at root level, to make it easier for Dirichlet noise to find new moves. I think a similar analysis could be mode for Go for example with a capture after a self-atari that has a very low prior, or similar knowledge holes.

**Comment by Eddh** [comment]
I've been wondering about that. From Alderi's 9x9 experiment it seems like it's not too bad (and maybe it helps that total_visited_policy depends on policy, and thus is influenced by dirichlet noise). But it does seem like it can be a problem that fpu itself (not just with reduction), acts as a very arbitrary gating on moves being picked, which seems to me like it could make it harder for the net to predict the search distribution. Would simply enforcing expanding all root nodes or half of root nodes be better ? The cost in terms of playouts may be too much, but who knows ? Anyway the same thing can be said of making fpu reduction 0 for root nodes. It makes it easier to discover new moves, but is it worth the cost in playouts ? I have no clue.

**Comment by jkiliani** [comment]
I think that forcing expansion of all or at least a significant part of root nodes may work quite well, and with the number of visits we're currently using the cost should not be prohibitive. But deactivating FPU reduction at root level may amount to the same thing.

Another thing worth consideration IMHO would be to delete all root nodes getting only a single visit from the training data, because that means that the search tried them and they're bad. So why not remove them from the visits distribution fed to the training data?

**Comment by gcp** [comment]
>I think not having dirichlet noise for the "forced" moves is a mistake. 

Again, Dirichlet noise is *always* applied.

**Comment by jkiliani** [comment]
What do you think about removing 1-visit nodes from the distribution used both for move selection with temperature on and for the training data?
