### ISSUE TITLE
Please explain what is going on at http://zero.sjeng.org

### ISSUE THREAD

**Issue by pw31** [leela-zero/leela-zero#1071]
Could you please update us on the strategy used recently on http://zero.sjeng.org?
The last regular promotion was 1ccb7342 VS b7768081 | 237 : 198 (54.48%), after 
which 1ccb7342 defended his title 17 times. But then, recently, 1cb39c46 came out 
of nowhere, has been beaten 3 times (marked as PASS) without the winners 
being actually promoted.
Is this testing of new blocksize/filter versions? When will we see one of these 
versions playing against current champion 1ccb7342?
Thanks!

**Comment by roy7** [comment]
Only games vs best network get promoted as new best network. The games vs 1cb39c46 were experimental matches that don't affect promotions/selfplay. I realize the table can be a bit confusing. I should probably change the sort order to stop using the # of games in the challenged network, since it can make test matches stick to the top of the chart.

**Comment by pw31** [comment]
Thanks.  But what is the nature of these tests, and is this related to a possible switch to new  blocksize/filter versions? Just curious.

**Comment by Eddh** [comment]
Yes these are tests of bigger networks and some are using another training method based on averaging weights.

**Comment by jthack** [comment]
@roy7 Maybe adding a "notes" column to the table where you can say if a set of matches is a trial run for a new network size. Also, it appears that the network size tests you did were pretty successful. There are pretty high win rates. How do you or @gcp decide which network size to pick?

**Comment by jkiliani** [comment]
It now looks like neither will be picked, but a compromise (sort of) which should be considerably stronger than either. However, that is still going to take a while, since @gcp now has to prepare a new bootstrap net which takes several days.

**Comment by Marcin1960** [comment]
I would recommend to place a short simple explanation on http://zero.sjeng.org/ in visible place like before word "Network 6615567e is a"

Clients and fans should not lose their enthusiasm.

**Comment by gcp** [comment]
>I should probably change the sort order to stop using the # of games in the challenged network, since it can make test matches stick to the top of the chart.

Given that it claims to show the 100 most recent it's pretty weird it does not sort on date.

**Comment by roy7** [comment]
It now sorts on date. Long ago when we queued matches for old networks there was a request to sort based on something else. So I started using the number of training steps of the opponent. This way it would sort matches on old networks into their proper place as if they had been run all along. 

But since test matches use more training steps than the best network until a new best network promotes, we had the reverse problem. Now it is back to simple date of match request order and the ancient match ordering no longer matters.

**Comment by jthack** [comment]
@roy7 you're the man! i bet we see half as many "WHAT'S WRONG WITH THE WEBSITE" posts and issues.

**Comment by Ikfes** [comment]
I'm also having hard time understanding the front page. There should be better tables and more explanations. I can set up stuff well enough to contribute in the project, but I dont know heads or tails about whats going on with the website and which hash is defending and which one is attacking and which one won.

**Comment by Ikfes** [comment]
Making the website easy to read, should be high in priority more people would join and contribute into the networks.

**Comment by sethtroisi** [comment]
closing, no active discussion for ~1year
