### ISSUE TITLE
Why using playouts instead of visits for self-play may be a Very Bad Idea

### ISSUE THREAD

**Issue by jussius** [leela-zero/leela-zero#1156]
So, I was just watching some AlphaGo games and as usual AlphaGo was making some weird ko-threat-like moves at very strange timings that seemingly had no meaning. Suddenly I realized that considering AlphaGo was trained using a constant number of playouts for every move while reusing the search tree, the moves and their timings actually made perfect sense. AlphaGo had simply learned to "reset" the search trees right when his opponent was needing a particularly deep search.

This is probably a much bigger issue than that of simply wasting ko threats every now and then. Obviously it means many playouts will be "wasted" exploring variations after those ko threats, but the issue becomes particularly pronounced when AlphaGo thinks she's behind and has to hope her opponent makes a mistake. At that point it may be beneficial to play moves that are simply bad/random, as a more random move causes a more complete "search tree reset", leading to a higher chance of mistakes in the subsequent moves. There are probably many much more subtle issues also caused by using playouts, like losing player avoiding one-way-street sequences during fights because the subsequent moves after the sequence will be very precise, or preferring sequences that give a lot of ko threats so they can be tactically used to reset the search trees at the right moment. Of course some of the capacity of the neural net will also have to be used to hold the skill of using these techniques, capacity that could hold actual Go knowledge.

Does any of this make sense?

I know Leela Zero recently started using visits instead of playouts in the self-play games. But I just wanted to post this because it may be of general interest as it probably explains many of the weird moves played by AlphaGo, and also because there has been some suggestions about moving back to playouts, which might not be such a good idea.

**Comment by Eddh** [comment]
The first paragraph doesn't make sense. If alphago had learned to "reset" the search tree, that means the policy networks will give a strong policy to the move which "reset" the search tree. But then that means this move will be the first move looked at, so it is a predictable move, so it is in the tree, so playing will move will not reset the tree to begin with. So the idea that alphago learns to reset the tree is self-contradictory.

Apart from that, it is very unclear to me if Alphago used tree reuse in self play games. The wording used seems to imply the MCTS search for each moves was independant to me. They also mentioned each move took about 0.4s to play. So that rules out visits + tree reuse. (And maybe tree reuse itself. Doesn't playing 1600 simulations take longer when they have to be done on top of an existing tree because of all the node to go through ? Please tell me if I'm wrong)

**Comment by jussius** [comment]
>The first paragraph doesn't make sense. If alphago had learned to "reset" the search tree, that means the policy networks will give a strong policy to the move which "reset" the search tree.

Well, when the neural network hasn't learned it yet, then it should be an effective technique, which should lead to the neural network learning it. Of course it becomes a less effective technique when the NN starts giving higher and higher policy to the ko-threat-like moves, so eventually it should reach a kind of an equilibrium where it sometimes uses the technique but sometimes doesn't. If there exists a way to manipulate the depth of your opponent's search, there's no reason why the NN wouldn't learn to exploit it one way or the other.

**Comment by billyswong** [comment]
@Eddh, in a game, usually there is more than one ko-threats usable on board. Splitting the tree onto those useless ko-threats reduce the search depth (of both sides) effectively.

**Comment by Dorus** [comment]
@jussius Very interesting read, however, i disagree with your conclusion that playouts are the root of these problems and visits would fix them.

First off, very few self play games have been released from AG/AGZ/AZ, almost all games i've seen from them are special games created for release and those are all played on some kind of time setting and not a fixed nr of visits or playouts. At best i could guess you mean that the program was trained on a fixed visit or playout count, and the knowledge it converted from the selfplay had an effect in match games.

That's my second problem: There is no "reset the search tree" in MCTS. At best a move that wasn't explored very intensely could be picked causing only a small part of the tree to be reused. However even if the expected move is played, most of the time that still means 30-40% of the tree is lost (or 50% with time management on), and since the other player moves too, that adds up to around 60%. Tree reuse is important, but no game changer that makes the bot play different. Rather it might play a little stronger or weaker in certain situations.

Another point i want to make is that i find it very hard to believe the NN can learn anything about MCTS. The NN never sees more than 1 board position and all "thinking ahead" is done purely by MCTS. The NN does not learn to analyse board position after a few moves like how a human would think about a game, but rather simulates this by analyzing one position, and then be ran again on another board position. But there is no link inside the NN towards the previous position.

The problematic behavior you describe all are known defects in MCTS. Also it's more prominent on weaker MCTS bots but even AG showed some of it. One main example is that MCTS bots try to push bad moves "over the search horizon". Meaning that if a forced 8 move sequence is going to lose the game, it might try to play a bunch of forcing moves first, even if those lose points, to end up with a 16 forced move sequence. If the MCTS only has enough time to analyses 15 moves deep (every move branched a bunch of times, so we're talking about x^15 here), it will prefer the bad forcing move over the proper reaction. Even if the proper reaction might still have a slight chance to win later on, while the bad forcing move leads to a certain loss. On the other hand, if it searches 16 movers deep, it might start finding the proper move.

**Comment by sethtroisi** [comment]
closing, no active discussion for ~1year
