### ISSUE TITLE
Network in minimax algorithm

### ISSUE THREAD

**Issue by TFiFiE** [leela-zero/leela-zero#1202]
As MCTS (normally) depends on unbounded memory, how would a network fare when used in a traditional iterative deepening search with alpha-beta pruning, using the value output for evaluation (obviously) and the policy output to determine how much to extend or reduce the search depth for a given iteration?

**Comment by tapsika** [comment]
There were some posts about such experiments on the computer go list. IIRC the results were somewhat similar to MCTS in strength.

**Comment by Akababa** [comment]
The Deepmind researchers claimed that MCTS tends to average out the NN approximation errors while minimax propogates the largest errors up to the root, although I don't know if they actually tested that.

**Comment by roy7** [comment]
MCTS has it's own issues I don't like, in how it averages things so when you find a refutation late you still have to take the bad move because of the # of visits in that path. I do find there research on better way to do the MCTS tree search interesting (like Thompson sampling) but those are for actual rollouts and don't directly relate to using NN evals because we have no variance info on our nn eval, only the average win rate with no other info.

**Comment by gcp** [comment]
>we have no variance info on our nn eval

You could presumable collect that info though.

**Comment by gcp** [comment]
>As MCTS (normally) depends on unbounded memory, how would a network fare when used in a traditional iterative deepening search with alpha-beta pruning, using the value output for evaluation (obviously) and the policy output to determine how much to extend or reduce the search depth for a given iteration?

It should work fine I think.

You can reformulate MCTS (or something extremely close to it) in a depth-first manner, and there's a Masters or PhD thesis on it, but IIRC it's unfortunately in Japanese.

**Comment by roy7** [comment]
> You could presumably collect that info though.

There are NN architectures that learn probability distributions instead of point estimates (NeuroBayes, etc) but since we don't use those I don't think I can estimate the confidence bounds of a single nn_eval from LZ. We can do lots of search in a branch and use an average of those results, that's how max_lcb_root does something, but mathematically I don't think there's any sound basis for that. It isn't like we're pulling the same bandit arm over and over (like in rollouts). We're pulling a different arm each time, once, and getting numbers that are correlated in some unknown way.

**Comment by sethtroisi** [comment]
closing, no active discussion for ~1year
