### ISSUE TITLE
Leela Zero will be in the 2018 AI Go Competition in Fuzhou

### ISSUE THREAD

**Issue by diadorak** [leela-zero/leela-zero#1220]
Is LZ optimized for competition already?

Google translate from a Korean Webpage 
http://www.tygem.com/news/news/viewpage.asp?pagec=&seq=31010&gubun=2&igubun=11

On the 27th and 28th of April, '2018 World AI Baduk Tournament' will be held in Fuzhou, China.

Eight teams will play in the Swiss league on the 27th, with a time limit of 30 minutes each. On the 28th, the semi-finals and the finals will be held and the finals will be held in the third. The time limit is 30 minutes for each person, 10 times for 20 seconds.

There are 8 teams in Korea, 2 teams in Korea (Stone wind, Gochu), 3 teams in China (Fine Art, Phoenix Go, TSGo), Japan 1 team (HEROZ Kishin) and 2 teams in Europe (Golois and Leela Zero).

What stands out is that there are two AI teams in Korea. My favorite is 'DolBaram' and 'LKGo', an emerging AI.

'Baduk' was developed by artificial intelligence developed by Professor Lee Joo-young of the Department of Computing Science at the Institute of Advanced Science and Technology and was only about four months old. Professor Lee Ju-young has visited the "AI Temple" held in Tokyo last year and asked other artificial intelligence developers about their usual questions.
Professor Lee Joo-young said, "I am aiming to win a prize because I have to confront the artificial intelligence that has been prepared and developed for a long time."

I am curious about the ability of Korean newborn AI 'Baduk', but Japanese AI 'Deep Zengo' developer said "Recently, the skill of Leela Zero 'in Belgium has been rapidly strengthened," so watching' Leela Zero ' It is a watching point.

In addition, there is also a confrontation of 'human-artificial intelligence', which is attracting attention because it will be the first place in China ranking and artificial intelligence 'Golaxy' will be big country. The intelligence 'Golaxy' is not yet known.

The '2018 World AI Baduk Tournament' will be held in Chinese rule and will be organized by China Baduk Association and Fuzhou City. The prize money is 100,000 yuan (about 17 million won), the runner-up is 70,000 yuan (about 12 million yuan), the third place is 50 thousand yuan (about 8,500 yuan), the fourth is 20,000 yuan (about 3.4 million won) Will receive 10,000 yuan (about 1.7 million won).

The AI ​​Baduk Contest will be held during the World Women's Baduk Contest, which will be held from April 26 to May 2.

**Comment by Friday9i** [comment]
Not a legal specialist, but to get the right to use Open Source code publicly and/or to make money with it, I thought the licence was forcing this user to publicly disclose the modifications done to the code... Isn't it the case?
And in the present case, can it be extended to modified networks? 
Otherwise, it seems to be totally unfair...

**Comment by hydrogenpi** [comment]
@Friday9i As far as code goes, you are completely right , but it comes down to enforcement and enforceability. I don't see gcp going after anyone, maybe I'm wrong, but I really just don't see gcp going after for example the LZ team, it would be bad publicity and serve a net negative

As for the network weights, that is murky legal ground, (I'm no lawyer myself) because are there any legal case precedents on derivation use of networks trained from community deep learning? The license only applies to the code,  but I don't see it covering all imaginable derivative use of that code. the training data is already public. But one could argue that there has been many people already training their own network based on the public domain training data and then NOT publishing them... but then again, these folks didn't really use them in public showcasings like what the golaxy vs lz matches are all about.

**Comment by Marcin1960** [comment]
Leela Zero in an open project on purpose. If someone does not like it, nothing stops him from joining some closed project.

**Comment by gcp** [comment]
I got asked about a month ago by two PhD students from China whether they could enter and operate Leela Zero for this tournament. I hesitated for a bit, because IMHO entering Leela Zero into competitions for computer go bots is somewhat besides the point and detracts from the project's goal. 

To me it feels pointless because you can literally take the weights and data (and even the code, depending on morals and tournament rules), improve it a bit (I suggest adding some go knowledge!), and you should have a stronger program if you understand how to test properly.

The problem of open source bots and competitions is not new. Computer chess has a particularly bad history with this and it's one of the reasons I went into go programming. In the end, it is up to the tournament organizers to set rules that ensure fair play and actually have the balls to enforce them. 

The phenomenon of these private matches with open source (or just public) bots and secret bots is not something I've seen before though. It may be a sign of the times when you can now "hide" the program easier behind online services, or simply super-corporations finding games useful for publicity (*cough* IBM *cough* Google). A program that the user can buy commercially can't really "hide" it's real strength for long, as the user can (and does, CCRL, TCEC, etc) run tournaments with it.

On the other hand, I considered that not entering doesn't do anything either, does it? By entering, we are a well known benchmark for the public and other teams to beat. I'd rather have more people finding out about the project, all things considered. So I gave permission to enter Leela Zero. I have not heard back, but I assume from the above at least it got entered somehow.

Anyway, my point, if anything, from all the above is that it is not worth getting too worked up over these kind of uses of the program, code and data even if it seems it occasionally allows other teams to score  "victories" or PR you consider questionable. A collaborative effort has the property that it can outlast secret projects and eventually bring more value to the users.

I don't know about you, but I'm still using Stockfish to analyze my chess games, and not Alpha Zero or Deep Blue.

**Comment by herazul** [comment]
Some guys here may have to see this awesome open source project more as a gift to humanity, that everyone can learn and improve and reuse than as a sport team to be defended tooth and nails in tournaments.
Still, it's fun to see her play versus other AI :D

**Comment by gcp** [comment]
>, but to get the right to use Open Source code publicly and/or to make money with it, I thought the licence was forcing this user to publicly disclose the modifications done to the code... Isn't it the case?

Only if you distribute the result.

**Comment by Friday9i** [comment]
"Only if you distribute the result": indeed, I had seen it but it was lost somewhere in my mind ; -)
In the present case, these people get "publicity" and probably indirect advantages (free trip, hotels, ...) by using the code: isn't it also covered by the licence, and shouldn't they at least communicate back to you what they do with the code and the networks?
Anyway, that's also some good advertising for the whole LZ team!

**Comment by gcp** [comment]
>As far as code goes, you are completely right , but it comes down to enforcement and enforceability. I don't see gcp going after anyone, maybe I'm wrong

If you think I would not try to enforce my copyright, you are making a risky bet.

Don't forget there are like 32 people who have copyrights on Leela Zero code. Any of them can enforce their copyright: https://github.com/gcp/leela-zero/blob/master/AUTHORS

**Comment by herazul** [comment]
>"Only if you distribute the result": indeed, I had seen it but it was lost somewhere in my mind ; -)
> In the present case, these people get "publicity" and probably indirect advantages (free trip, hotels, ...)

I don't think it matter much, for us at least, it's up to the tournament organisers to look for that if it bother them.

**Comment by gcp** [comment]
>I don't think it matter much, for us at least, it's up to the tournament organisers to look for that if it bother them.

Exactly. 

PS. If someone would take what is obviously a modified LZ and win the first prize, what do you think the other teams in the competition are going to say about that? It's not so much our problem.

**Comment by gcp** [comment]
>because are there any legal case precedents on derivation use of networks trained from community deep learning? The license only applies to the code, but I don't see it covering all imaginable derivative use of that code. the training data is already public.

FWIW all networks that come off of my training machine should be considered public domain, at least that was the intention. I don't think it makes sense to do otherwise as the training code and data to generate them is already public domain too.

I can't speak for the 256x20 that were contributed. I assume there's at least an implicit license to serve them off of zero.sjeng.org.

**Comment by Marcin1960** [comment]
@hydrogenpi "argueably it could be worth it if the larger goal is that of max strength regardless of the means"

Nope! You miss the point of open free software.

" As our society grows more dependent on computers, the software we run is of critical importance to securing the future of a free society. Free software is about having control over the technology we use in our homes, schools and businesses, where computers work for our individual and communal benefit, not for proprietary software companies or governments who might seek to restrict and monitor us. The Free Software Foundation exclusively uses free software to perform its work.

The Free Software Foundation is working **to secure freedom for computer users by promoting the development and use of free (as in freedom) software and documentation**—particularly the GNU operating system—and by campaigning against threats to computer user freedom like Digital Restrictions Management (DRM) and software patents."

**Comment by LetterRip** [comment]
"The networks and training data are public domain."

It isn't clear that in the US they could even be subject to copyright.

**Comment by alreadydone** [comment]
Machine Learning As a Service (MLAS) is becoming popular because of its versatility. These applications typically have high computation and data-storage requirements, which make them less suitable as client-side technologies. Moreover, since **the process of training a cognitive model is time and resource-consuming**, the trained prediction algorithm is often considered **critical intellectual property** by its owner, who is typically not willing to share its technology or proprietary tools, resulting in that machine learning algorithms are most conveniently cloud-based.
from https://eprint.iacr.org/2017/1114.pdf

**Comment by Marcin1960** [comment]
@LetterRip  It isn't clear that in the US they could even be subject to copyright.

It is a subject to copyright. To a very special kind of copyright - GPLv3:

https://www.gnu.org/licenses/quick-guide-gplv3.html

**Comment by Mardak** [comment]
GPLv3 is a "copyleft" license that grants permissions to copy / distribute things subject to copyright, e.g., source code. I believe data / numbers by themselves are not copyrightable, but their presentation can be. I would think networks and games fall into "data" and are public domain.

**Comment by gcp** [comment]
Collections of data (or games) are definitely copyrightable.

**Comment by hydrogenpi** [comment]
Yeah that is why gogodatabase sells their collection for $15 even though they don't own any of the games. It is the art of making a selection /set that is copyrightable in and of itself.

**Comment by diadorak** [comment]
@Friday9i I am shocked that you think they attempt to make profits on LZ. From what I learned in the QQ group they are in, the participants are the same guys who are running LZ for the Golaxy game. They have been running their 5x1080ti and 4xtitan v machines 24x7 for months to contribute to the project. I imagine their electricity bills are substantial. 

They are not getting free trips or hotels. The organizer does not pay for flights or hotels. They are paying  out of their own pockets to promote Leela Zero.

Poor communication? Definitely. 

Profiting from LZ? Hell no.

**Comment by hydrogenpi** [comment]
now that leelaz is bona fide top pro level, the value prop of any commercial Go engine is nil. crazystone and others are too late already. sure its a bit stronger than LZ, but not enough to salvage a business model

**Comment by l1t1** [comment]
http://sports.sina.com.cn/go/2018-04-19/doc-ifzihnep9080165.shtml says
by google translate 
**Leela Zero: Leea Zero is a faithful implementation of the AlphaGo Zero thesis. It uses Monte Carlo Tree Search (MCTS) and deep residual convolutional neural network stacks. It does not require the input of human chess, and can constantly improve the chess force in self-taught. Leela Zero is led by Gian-Carlo Pascutto, the Belgian programmer and author of the famous Go software, Leeela. The global IT industry elite trains the weights of the network and volunteers assist in running the spectrum. It is the most widely used open source distributed Go project.**

**Comment by Friday9i** [comment]
@diadorak: a precision, I don't "think they attempt to make profit from LZ", to be honest I don't know the situation, so not in a position to judge at all. I'm just saying that there is a theoretical possibility that some people will try to benefit from LZ to get publicity, awareness or money from this collective work: if it's also a good publicity for LZ, it's tolerable; if not so much, that should be stopped or at least the relation should be modified (eg applying the licence and asking them to give back the full modifications of the code).
In the present case, if they run machines for months to contribute and are running a strong machine for the tournament to show the world how strong LZ is, it seems fair IMHO. If they just come with a strong machine, use LZ, beat the opponent and then speak of themselves and their machine more than from LZ, just to get publicity, that's more than doubtful.

**Comment by gcp** [comment]
>now that leelaz is bona fide top pro level, the value prop of any commercial Go engine is nil. crazystone and others are too late already. sure its a bit stronger than LZ, but not enough to salvage a business model

Offering a UI, ease of installation, analysis features, 9x9, odd komi support, Japanese "rules", etc, are more than enough to "salvage a business model". Fritz and ChessBase still sell. Stockfish runs great under them.

**Comment by hydrogenpi** [comment]
In general its true that there are ancillary things that can still be profitably marketable. But as for the engine itself, imho at this point LZ is already strong "enough" that even if it were to make zero more progress from here on out, and even if the likes of a new CrazyStone was much stronger, the gap would be not able to return things back to the golden good old days of CrazyStone 2013 before AG and before the use of DCNN for Go. That market is gone for good. Which can be doubled edged but I think it is for the best. 

As for UI, unless CrazyStone did something new, their previous products demonstrated UI was not their strong point. there is no DPI scaling and it looks horrible on 4k monitors etc and just in general seems like a Windows 98 interface style. Now with Sabaki and Lizzie to the scene, it remains an open question whether or not even UI in Go can sell or be marketable. 

But as for analysis features, sure that is sorely lacking right now, so is odd komi support, or other things that were mentioned and even outside the box stuff like a nature language Go AI teacher that provides verbal feedback per move/game etc

**Comment by gcp** [comment]
>From what I learned in the QQ group they are in, the participants are the same guys who are running LZ for the Golaxy game.

From my email, they know each other but it's not the same people. Aaaanyway, I'll send them the guidance I can regarding "test things exhaustively in advance not during the tournament" and "only consider statistically significant results when doing not-default things" and I hope some of it takes hold and lessons were learned from the Golaxy debacle.

**Comment by roy7** [comment]
This the one taking place now?

http://portal.yikeweiqi.com/online/golive/index.html

**Comment by LetterRip** [comment]
@gcp 

> Collections of data (or games) are definitely copyrightable.

They are computer generated and particularly they are the result of randomizing inputs, and thus there is no 'creative' step in their creation.  So the games themselves probably are not copyrightable material.

The games are aggregated by date of creation, so there is no creativity in the creation of the aggregate data.  So again probably no copyrightable interest as a collection.

The lack of a creative step is important in determining whether there is a copyrightable interest.

I'm not a lawyer, but I've read enough copyright law and copyright case law that I've got a pretty reasonable understanding of the subtleties.

You can have copyright over the networks you train (probably - untested territory I think).

If you really care about the question you can contact the Software Freedom Law Center.

https://www.softwarefreedom.org/about/contact/

**Comment by sethtroisi** [comment]
Looks like LZ took 3rd, https://github.com/leela-zero/leela-zero/issues/1271
2019 will be even more exciting
