### ISSUE TITLE
Phoenix Go team interview

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#1283]
http://www.yikeweiqi.com/interview/44310/

**Comment by l1t1** [comment]
they said 
1.selfplay is on servers without gpu, but generate network use gpu 
2.the program on home PC can beat some AI

**Comment by hydrogenpi** [comment]
@bjiyxo I concur with the logic that 40 block is doable. Do you have plans to start a net2net from scratch a brand new 40b 256 filter from the latest #128 network aka the latest 15 block and then train forward all the 10 block and 15 block and also (in the future 20 block) games training data to perfect a 40 block in preparation for the time and day when it comes to make the final switch?

**Comment by bjiyxo** [comment]
Yes, I have some plans to train 40 blocks, and I will still keep training 20bx256f, too.

**Comment by WYVYW** [comment]
@hydrogenpi: What happened to your 40 b ?
"Thanks 阿尔克杰诺 aka @Grotex I got your 40b 256f and can confirm its a good net, and its working fine! No heatmap issues. Now it just needs to be trained to be stronk! lol

**Comment by hydrogenpi** [comment]
@WYVYW the truth is incompence happened, i can figure out how to do it on linux and its not working on windows. i am trying to watch some deep learning and tensorflow videos on udemy and with the latest multigpu code perhaps i can try to start a net2net of the current 129 network to a 40b 256f and backtrain the latest 10b and 15b games. my hunch is because bjiyxo started with a 78 net 6b that is what is keeping his 20b from getting even stronger. but good to see he is open and amenable to starting a 40b, i just hope he agrees to net2net the 40b from latest 129 network instead

**Comment by jkiliani** [comment]
I think it's actually rather likely than @bjiyxo's net is strong because he started on 6 block data. This way, his net has "seen" everything that happened in Leela Zero self-play since then, and adapted to using the stronger policy moves for cases when there are examples to do so.

It's hard to say what the ideal dataset/training strategy for a bootstrap network is, but the performance of the 20 block net rather supports @bjiyxo's approach here.

**Comment by Splee99** [comment]
An extreme ladder will take (less than) 35 steps from one corner to the diagonal opposite corner. So I think a 30 block net maybe strong enough to cover all the issues we have right now.

**Comment by sethtroisi** [comment]
closing, no active discussion on older issue
