### ISSUE TITLE
there are too many lz_ELF bots on cgos

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#1322]
one win all the games 
http://www.yss-aya.com/cgos/19x19/cross/LZ-ELF-gtx1080-LCB.html

but the second lost to 2 weak bot
http://www.yss-aya.com/cgos/19x19/cross/LZ-ELF.html

**Comment by Eddh** [comment]
It seems like without Zen there is no other "anchor" bot for the > 3500 elo range. Seems to be a problem too.

**Comment by l1t1** [comment]
could somebody setup a bot of LZ131 at  cgos?

**Comment by tterava** [comment]
There's no high level bots in CGOS currently so I turned LZ-ELF-gtx1080-LCB off for now. I'll see if new bots with higher rating appear later.

**Comment by hydrogenpi** [comment]
My guess is no one wants to spend the cycles to run their bots just to get defeated by LZ-ELF-gtx1080-LCB

sign of the times.

**Comment by MaxMaki** [comment]
All the Zen bots have been disconnected already for a while, same as the Leela 0.11 anchor around 3000.

There was a gap months ago when they all disconnected, and it was posted on the computer go mailing list that the people running them didn't really feel like continuing since it had become a LZ testing ground, with a huge amount of clones running.

To make things worse, most weren't even run for 100 games, and extremely few were run past 100 games.

What do you think that happens to a rating system like CGOS when all the strong bot operators run the bare minimum of 100, taking advantage of the Zen bots, and just skewing the system? It dies. Maybe the Zen bots have disconnected since the Zen author has stopped developing, but fact is, many have completely abused the system running for the bare minimum amount of games while not caring one bit to "spread the love" and help the rankings be stable. 

There are of course exceptions of a few people running some LZ anchors and JinSiWeiqi running for 2000 games. But most strong bots have just enjoyed the free buffet of a minimum of 100 games...

**Comment by l1t1** [comment]
http://www.yss-aya.com/cgos/19x19/cross/LZ_62b541_ELF_1600.html
Rated: 3486

**Comment by 2ji3150** [comment]
What is 1600? -v 1600 or -p 1600 ? It is cofusing.

**Comment by l1t1** [comment]
I don't know, @tterava may know

**Comment by tterava** [comment]
I'm not running that particular bot.

To be fair, I don't think 100 games is "hit and run". If that's too little, there's nothing stopping the CGOS admins to raise the limit to 200 or whatever they wish, before bayes elo is calculated.

I added an ELF-bot with 10 playouts (-p) so there's another anchor at 3k+ (hopefully), as running it is basically free.

**Comment by yssaya** [comment]
I run LZ_62b541_ELF_1600 and LZ_158603eb_1600.
Both are "-p 1600".
And LZ_62b541_ELF_1600 is 800 playouts if over 300 moves. And 400 playouts over 400, 200 playouts over 500 for timeout.

bool UCTSearch::stop_thinking(int elapsed_centis, int time_for_move) const {
    int n = m_rootstate.get_movenum();
    int x = m_maxplayouts;
    if      ( n > 300 ) x = x/2;
    else if ( n > 400 ) x = x/4;
    else if ( n > 500 ) x = x/8;
    return m_playouts >= x
//    return m_playouts >= m_maxplayouts
           || m_root->get_visits() >= m_maxvisits
           || elapsed_centis >= time_for_move;
}

**Comment by l1t1** [comment]
when i wake up, nearly all the bots equip the elf weight, so it become the compare of hadware and config parameter

**Comment by l1t1** [comment]
someone post a reply on tieba

-
It feels like the official AI competition is now almost the same. If anybody later makes any substantial improvements in the algorithm, he or she should immediately go to the cgos or game platform to test it. It is advisable to publish the algorithms and weights after confirming that the results are satisfactory. This will not only achieve results sharing but also establish their own status. The time of the AI contest is not a node. Anyway, the prize for the AI competition is not much higher than the training and entry cost, and the top AI is not that difficult to find the top career chess.

**Comment by l1t1** [comment]
rn renamed to rlo
https://github.com/gcp/leela-zero/issues/1358
