### ISSUE TITLE
The 'good playing attitude' of LZ

### ISSUE THREAD

**Issue by Hayden2018** [leela-zero/leela-zero#1474]
I observe that LZ networks are able to generate very sensible moves even at very low win rates.(1-2%) While Elf net work is stronger then LZ in even game, it generate garbage when win rate fall below 3%. So it is much weaker than LZ in handicap games. 

I also heard that LZ is able deal with ladders at high play outs. While Elf tends to avoid ladder passively instead of dealing with it.

These properties certainly make LZ more suitable for training human and analyzing human games than Elf. I wonder why LZ was able to learn this virtues while Elf does not. Would it be possible that LZ lost these good properties after prolonged training with Elf games?

**Comment by Mardak** [comment]
There's been some speculation on Discord that this is the natural progression of self-play after many network promotions. Basically, self-play learns to play against the best version of itself, and on average, even with T=1 (but especially with T=0 after 30 moves), self-play data reinforces that the opponent will play a very strong move as a response leading to "certain" loss.

Potentially this is a counter-point to #1416 proposing 800 visits as there's been some guessing in that issue as well that LZ has learned ladders because it can search deep enough to figure out when a ladder is a winning or losing play. To be clear, lowering the visits could definitely help be more optimal in generating training data while the network is still learning / promoting, but as it reaches ELF levels, it might make sense to search deeper to try to learn something different.

**Comment by sethtroisi** [comment]
closing older issues, no discussion for >6 months, more discussion in other threads.
