### ISSUE TITLE
suggest to not push resign-0 game to weak machine 

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#1509]
just as not push them match games
as one game cost several hours , they cannot contribute a few in a day.

**Comment by Ishinoshita** [comment]
Agree. I use a CPU machine and had several time to stop autogtp because I got a no-resign game pending for hours and do to consume many more. Feels bad to have to do that in the middle of a 600+  moves game.... Pure waste. Theoritically, while my weak machine chews for hours on a single no-resign game, this allow another strong GPU machine somewhere to produce many many resignable games. But practically, it is very inconvenient for weak machine owners to contribute in this conditions.

**Comment by LRGB** [comment]
Yes, I was meaning do ask for this. Please do!

**Comment by Hersmunch** [comment]
As far as I understand, training data is used on a per move basis i.e. the data from a resign game is contributing as much as as the same number of moves from resign enabled games.
The reason for limiting match games to faster machines is because it is useful to know the results as soon as possible. It doesn't really matter that training data arrives slower.

(btw server issues are best raised here https://github.com/gcp/leela-zero-server/issues)

**Comment by Ishinoshita** [comment]
@Hersmunch: Even if training data are used on a per position basis, completing a position training sample need the game outcome as target for each position in the game. So I understand that the whole set of positions/traing target gathered during a selfplay game is  lost if the game is aborted and cannot be resume in a timely manner (strangely, I've observed some game resuming, some not. Question of delay ?).

**Comment by Hersmunch** [comment]
I agree about losing the data but are you aware of these autogtp options?
```  
-t, --timeout <time in minutes>       Save running games after the timeout
                                      (in minutes) is passed and then exit.
-s, --single                          Exit after the first game is completed.
-m, --maxgames <max number of games>  Exit after the given number of games is
                                      completed.
```
Whilst games are being played there is also the ability to input "q" and then "Enter" to save training data and exit (wait for it to save before closing the window). If there is saved data on start up then autogtp will continue with that when it is next run.
Or is your concern about machines being powered down mid-game?

**Comment by l1t1** [comment]
i used the q option, but it often resume the older weight's game when new one occur

**Comment by marcocalignano** [comment]
@l1t1 can you elaborate a bit more on this last comment?

**Comment by l1t1** [comment]
eg. i press q at last Friday, today autogtp downloaded the lz 147 wight, and resume the lz 145 self play

**Comment by l1t1** [comment]
nothing wrong, i just  elaborate that thing.

**Comment by jokkebk** [comment]
It's a nuisance on slightly faster machines as well, I have GTX 1060 and it takes 20 mins or so per game that allows resign (say 150 moves avg, some end quickly with randomness, others don't), and 2 hours for a non-resign game (that usually takes about 600 moves).

Is the random sampling per move, or first per game and then random position? In the first case, having 20 % no-resign games results them being almost 50 % of training positions. In the second, it's wasting most of the GPU time as the situation really doesn't change after the 300 or so moves are played.

Could there be some heuristic after 300 moves so that every 50 moves it checks if one is 50+ points ahead and the other feels winning percentage is less than 0,1 %, so it would spend like half the visits after that? I doubt it degrades the quality of these junk games.

And I have to say that the no-resign games are hurting my motivation to contribute, I had to turn LeelaWatcher off because the no-resign games take so long that close to 50 % of time when I go check my (main) computer, it's again filling it's own eyes at move 550... 😞

**Comment by l1t1** [comment]
my final solution is once find a resign-0 task, then cancel it by press ctrl+c, and rerun autogtp, until i get a resign-5% task
