### ISSUE TITLE
Replace UCT with small neural network.

### ISSUE THREAD

**Issue by typohh** [leela-zero/leela-zero#1575]
UCT algorithm for choosing which branch to explore next appears to be somewhat sub optimal in practice. As an easy proof of concept I trained a very small neural network to replace it and in the synthethic test bench (which mimics go settings) it outperforms both leelas version of UCT as well as standard UCT. Ill be tinkering it with some more and will plug it in leela to see if it improves the results in practice by any meaningful margin. Will these kinds of improvements be accepted into the official branch if proof of improvement in real settings is demonstrated or will leela stick to vanilla version of everything?

**Comment by Eddh** [comment]
How did you train it ?

**Comment by Friday9i** [comment]
Oops, Deepmind dit it (again)! Is it the same approach? https://deepmind.com/research/publications/learning-search-mctsnets/
Anyway, that's extremely interesting @typohh, waiting for more results from you ; -))).

**Comment by typohh** [comment]
@Eddh 

For testbench built a multiarmed bandit, one exploration of a branch returns the average winrate based on x samples, and provided policy is based on results from y exploration at each branch. Then searched for x and y whose accuracy matches those provided by leela in actual game positions (so as to mimic practical policy and value network errors). Run for z rounds (0-3200). Finally use same criteria as UCT for selecting which branch wins (the one with most visits). Then compare underlying winrates for  winning branch and best branch. 

In any case, just wanted to test if it would improve the results and it di.... 

@Friday9i 

thx, good to know I don't have to explore this idea any further. and yes its very similar idea tho they took it quite a lot further. in any case it's probably something leela should consider implementing.

**Comment by Hersmunch** [comment]
https://github.com/gcp/leela-zero/issues/1109 may be of interest

**Comment by Friday9i** [comment]
@typohh not sure to follow you when you say "thx, good to know I don't have to explore this idea any further"... On the opposite, it's a promising idea tested by Deepmind and giving good results, hence that would be a pity not to explore it more, isn't it?

**Comment by Eddh** [comment]
@typohh I understand the goal is to essentially replace uct_select_child() in LeelaZero by a NN, but I don't understand the details of your NN. The inputs are the position, and for each possible move, the q value of each move, the number of visits, and the policy right ? But then for the training target I don't understand. Ideally it should be a "bandit network", picking the move which would yield the best reward, so the best leaf result ?

**Comment by typohh** [comment]
@Eddh in uct_select_child replace the way value is calculated for each child. Use the same inputs just pipe them into an NN to get the value instead of uct formula. Then yrain for long term rewards. Which means balance exploration and exploitation in the best possible way with the information available.

**Comment by Eddh** [comment]
OK I understand better. I'm curious how well it would fare in play.

**Comment by Tsun-hung** [comment]
It sounds a novel work, could it be a effective modification to improve the strength of LZ?

**Comment by pangafu** [comment]
I think it maybe work, we can try~

**Comment by TFiFiE** [comment]
The neural network better not be too expensive or it might very well be an improvement with equal visits, just not with equal time (like #883).

**Comment by pondturtle** [comment]
Why not try different sizes of "helper" network and testing them against LZ as is and each other? that way we could try to determine where the sweetspot is.

**Comment by gcp** [comment]
>Will these kinds of improvements be accepted into the official branch if proof of improvement in real settings is demonstrated or will leela stick to vanilla version of everything?

This sounds like MCTS-Nets.

If it's stronger than the normal UCT at equal time settings then I don't see why we wouldn't take this, as long as some assurance can be given wrt. some minimal amount of exploration as the current noise and T=1 achieve.

**Comment by keldor314** [comment]
This may be a big win in some other ways.  Consider that there's a group on the board that might be alive or dead, but the situation is a bit too complicated to tell easily (i.e. Leela would need to do some playouts to find out).  Now suppose that it's too early in the game to think about saving or killing the group, since there are definitely more important moves elsewhere.  Wouldn't it be nice to know what the status of the group actually is so you can plan your large scale strategy accordingly?

The problem is that Leela won't read this at all unless it thinks that attacking or saving it is the best immediate move right now.  This can have some nasty effects if Leela has to play on without being certain, or with possible bad moves if Leela "cheats" and the network is pushing this sort of move up in win probability since it's learned that it can read it out that way, thereby actually increasing winchance.  Neural networks are notorious for finding sneaky ways to cheat the system.

All this also applies to ladders, which might not be read out at all if they're not immediately important, leading to nasty surprises further down the line.

This also might be part of the reason networks start doing really bad moves when they're behind.  If you assume that they're effectively manipulated themselves to perform readouts in life and death situations, it's possible that whatever immediately threatening moves that it wants to read out are the only remaining ones after the more hopeful moves have been weeded out.  This might explain why AIs tend to like to play strange ko threats when they're behind.

Ideally, using a network to guide reading would let it learn to read moves that, while not urgent right NOW, have important positional ramifications later on.  Ladders, just how solid a given small group would be in a potential fight, and so forth.  Such a network should also be provided data about the current time settings.  If it knows it only has time for 6 more evaluations, it might choose a less complicated area of the board to analyze compared to if it has the time budget for 600 evaluations left.  Since every system runs faster or slower depending on hardware, profiling to calculate the number of network evaluations rather than just the seconds left on the clock is a much better way to do it.

**Comment by tterava** [comment]
> The problem is that Leela won't read this at all unless it thinks that attacking or saving it is the best immediate move right now. 

I don't believe this to be true. The policy head gives moves which LZ thinks are important to search (this is different from moves with highest winrate) and if it's unsure whether a group is dead or alive, it certainly tries to find a move to kill it. Finding that move would probably decide the game so it should have very high policy prior. If the group is already alive, then LZ plays something else. On the next move LZ is again on a situation where there's a group on the board it's not sure about, but because LZ is fed previous 8(?) moves from the game, it can assume that there's no move to kill the group because it wasn't played last move. If a move is played that can affect the status of the group then it can decide to give high policy prior to the possible killing moves again. The past played moves work as a memory from which it's possible to deduce the status of a group without recalculating it every move. I'm assuming that LZ has learned this behavior, but based on its super human performance I would be extremely surprised if it hasn't.

> This also might be part of the reason networks start doing really bad moves when they're behind.

Trying to stall a losing game is actually the optimal way to play from game theory perspective. There's multiple benefits to it: 
- It gives your opponent chances to do a mistake
- It gives you more time to find something that might turn the game
- If you are about to lose the game anyway, then playing these moves certainly won't make the situation worse.

You never want your program to deliberately play into a losing sequence, so the only option is to stall and hope for a miracle. Humans don't typically do this because we value our time and consider it polite to resign when we think there's very little hope. When LZ starts doing these nonsense stalling moves, it's basically at the point where it cannot see any reasonable way to win anymore (assuming the opponent is of equal strength as LZ) and you should set a resign threshold if you don't like this behavior. That's why LZ starts playing totally weird with high handicap: If all moves have effectively 0% winrate then it doesn't matter where you play. The selection is mostly random at that point.

**Comment by Marcin1960** [comment]
I used to provide in my bot, winrate information to the users. What value should I pick now?

**Comment by sethtroisi** [comment]
somewhat related to https://github.com/leela-zero/leela-zero/issues/1295

**Comment by sethtroisi** [comment]
closing >6 month old issue with no clear owner
