### ISSUE TITLE
Manual pruning capability

### ISSUE THREAD

**Issue by TFiFiE** [leela-zero/leela-zero#1675]
As a way to make LZ more useful as an analysis tool, what about introducing a (real-time) option to disregard moves from the search? Nodes can already be deactivated by the time management, so it wouldn't even have to be an intrusive change.

**Comment by gcp** [comment]
uci searchmoves?

**Comment by TFiFiE** [comment]
I think it makes more sense with Go engines to indicate what to exclude rather than what to include.

**Comment by dfannius** [comment]
Do you just want to exclude certain moves at the root position, or do you want all play to be in a local area for a while (e.g., solving a tsumego problem)?

One possible problem with the former could be that it might want to just make a sente exchange where it's allowed to and then come back to the area it really wants to play in. One possible problem with the latter is that the policy and value heads assume that moves can be played all over the board, so they might be silently assuming a followup outside of the constrained region and be very incorrect as a result.

These problems are all hypothetical for now, of course.

**Comment by gcp** [comment]
>I think it makes more sense with Go engines to indicate what to exclude

That's a good point. We should add this, because unlike include moves this can't really be sensibly handled by playing out moves and checking the evaluation after that.

**Comment by betterworld** [comment]
I implemented a feature to avoid moves and it seemed to work just fine during my first tests.

Regarding @dfannius' comment, in order to avoid a "quick sente exchange" before the forbidden move, I included a feature to forbid a certain move to be played for the next N moves.

E.g. the gtp command "avoid b q16 +8" makes Black ignore the possibility to play q16 for the next 8 moves.

**Comment by roy7** [comment]
Hey this could be awesome for my bots who sometimes lose to people passing too early and trying to get a win from the auto score when the board is mostly empty. In theory then I could do like "avoid b pass 90" would prevent black from passing in the first 90 moves of the game? (Say my bot is black.) This way if an opponent starts passing at move 30 I'll just keep playing more stones.

**Comment by wonderingabout** [comment]
@betterworld @roy7 
great idea

**Comment by AncalagonX** [comment]
This is a simple yet excellent feature that can be used to greatly improve game review in tools such as Lizzie. There are many in-game situations and other reasons why a user would want to forbid a move from consideration and force LZ's efforts elsewhere, and I've quietly wished for a function like this a number of times in my games.

It also would allow for more creative players to do things like solve tsumegos as mentioned above, or forbid common opening moves like 3x3 invasions, or force LZ to always begin on Tengen as black, and so forth.

**Comment by AncalagonX** [comment]
I'm finishing up a simple PR along similar lines of thinking that allows the user to widen (and narrow) LZ's search on-the-fly during pondering, intended for use when reviewing games with tools like Lizzie. Having the search width modifiable mid-ponder has the benefit of allowing the human reviewer to see numerous other reasonable and perfectly valid moves that could be played for any particular board state, rather than the usual case of LZ only sending visits down the PVs of its one or two ultra-optimal, superhuman moves.

I've been using this "modify search width" feature locally for quite a long time, and it works excellently. I'm ironing out some final details but the PR is quite simple, and I'll be submitting it within a matter of just a day or two.

**Comment by TFiFiE** [comment]
@AncalagonX, would your changes allow for the possibility of forcing the engine to start out visiting all possible moves for a given number of visits (as requested in featurecat/lizzie#321), because I was planning of creating a PR for that myself?

**Comment by AncalagonX** [comment]
@TFiFiE I've done that before and it only requires a few extra lines in UCTNode.cpp. I'll share the simple changes with you later today.

**Comment by TFiFiE** [comment]
I already have some code to do this, but if what you have is a generalization of this functionality, I want to avoid conflicting pull requests.

**Comment by AncalagonX** [comment]
@TFiFiE Feel free to reach out to me on the Leela Zero Discord. I can be found there daily.

Here are two methods for forcing LZ to explore every intersection equally: [Force_Equal_Root_Visits](https://github.com/AncalagonX/leela-zero/tree/Force_Equal_Root_Visits). It's also trivial to add a per-intersection visit limit for when it should stop exploring every tile and return to spending visits on normal LZ search. (If your code is implemented using a different method, I'd be interested in seeing how you did it.)

Though if the intention here is to assist game review by enabling a wider search, there are much better methods than visiting every square equally. I'm finishing this up now, and you can see the current progress in the [LZ_Review_Mode](https://github.com/AncalagonX/leela-zero/tree/LZ_Review_Mode) branch. The code is extremely minimal, fully functional, and already performs the intended task very well (showing many more highly-rated variations) in its current state.

Before I open a formal PR, I'm doing a bit of extra legwork to try to make use of the `PUCT/policy` scores as well. This would help eliminate a minor side-effect of spurious/wasted visits when conducting wider searches on a board state that only has a small number of truly viable moves (i.e. when responding to a forcing move).

**Comment by TFiFiE** [comment]
I just went ahead and made [the pull request](1953).

**Comment by gcp** [comment]
As I commented, the "analyze every move" can already be achieved right now, so I am not adding support for it in the engine again. It sucks that it's apparently hard to implement in the current Lizzie design but even that would never ever warrant this.

>I'm finishing up a simple PR along similar lines of thinking that allows the user to widen (and narrow) LZ's search on-the-fly during pondering, intended for use when reviewing games with tools like Lizzie.

Much the same thing applies here, changes which involve making LZ's own search suboptimal are very likely to be misguided.

Instead, try to think about what is needed to achieve this GUI side. I think that if you have the move priors, you can do the same thing again and go into those moves and just run the normal search (maybe with the visits scaled by the prior). But one issue here is that we don't send out priors for moves that got no visits. Maybe we should send out a minimum amount, or any prior that isn't more than some fraction worse than the best.

Alternatively, you could incrementally add the best moves to the exclude move list to force the search to open more widely that way. I think this would behave even better in practice?

**Comment by gcp** [comment]
>If you want it to keep pondering (say 100 playouts to each move at a time) all the moves you'd have to go back and forth between all hundreds of moves.
>Additionally it will not work at all because leelaz is prunning a tree immediately after you play a move.

I suspect this is not an issue because of the NNCache: reconstructing the tree should be very fast unless its huge (which doesn't sound like a typical use case as they will be 1/300th of the normal size!).

**Comment by gcp** [comment]
If this turns out not to work (i.e. the NNCache is not usable), then perhaps it would be more useful to expose a selectivity parameter that controls both PUCT and policy softmax. I'm saying this because even for investigating "unlikely" moves it's probably more interesting to have a wider search in general, rather than uniformly doing investigation at the root (which is very inefficient).

But should that selectivity then control the root only, or the entire tree? It's this kind of messing with the search behavior that I'm not a fan of :-/

**Comment by AncalagonX** [comment]
Widened search cannot make LZ stronger (papers have been published on this very topic), but it serves an invaluable role in game review and variation exploration. I've been experimenting at least as far back as April with a variety of methods for widening and narrowing LZ's search on-the-fly using GTP commands so that LZ can output accurate information on more variations than just LZ's optimal choices.

I've settled on two primary methods that stand out above the others: 1) Limiting max visits for any root move to a user-configurable percentage of total visits conducted so far; and 2) Adding a user-configurable multiplier to PUCT on root moves so that LZ explores a wider selection of its high-policy moves.

Surprisingly, the "cruder" implementation of limiting visits to a maximum % of visits conducted (where the per-root-move visit limit grows proportionally as more total visits accumulate) has consistently proven *vastly* superior and informative compared to any schemes involving altering PUCT at root.

I'm finishing up a branch that implements LZ search that can be widened or narrowed on the fly as the user wishes by limiting the maximum number of visits any root node can receive to a certain percent of total visits performed so far. The code is quite minimal, it doesn't alter LZ search other than redirecting visits to the very next best root move or moves LZ would have otherwise preferred to investigate, its search width can be changed on-the-fly in the middle of pondering, and most importantly it performs the wider search and generates useful results exactly as intended.

I will post detailed comparisons of the "limit root node visits to % of total visits on a sliding basis" method, versus the under-performing "modify root PUCT" method, alongside comparisons of the unmodified LZ search when I post the PR. This will make the pros and cons of each implementation readily apparent for the valuable function of shaping LZ's search.

**Comment by AncalagonX** [comment]
@gcp Yes, regardless of which wider search implementation one is considering, root is the only place you want to modify. LZ should simply conduct regular, unmodified search when `!is_root` like usual. This lets LZ perform a full-strength assessment of whichever root moves are included in the wider search, and works as one would expect: it returns a confident answer, backed up by many unmodified LZ visits, of the `winrate` of a particular root move.

When LZ's search is modified deeper than just the root node in an attempt to widen the search, it usually leads to results that are undesired, very weak, or plain broken.

**Comment by gcp** [comment]
>Expecting these kinds of search modifications from the gui means they need to be written for all guis again and again, and that they are not available without a gui

This is fine and a very good argument **in favor**. It means the GUI has control over the analysis feature and can do whatever it thinks is the best for whatever task the user is requesting of it, rather than being hard locked in to whatever decision we make now.

**Comment by gcp** [comment]
>As you correctly suggested, when LZ's search is modified deeper than just the root node in an effort to widen the search, it usually leads to results that are unuseful, extremely weak, or just plain broken.

OK. Then I would consider adding a ```Root Selectivity``` option to lz-setoption, working on a scale from 0 to 100, and defaulting to 80 or 90 or so.

What **exactly** this controls inside the engine is not defined, and depends on your experiments. The user should not care, he can just change the setting in the GUI.

Does this achieve what you and @TFiFiE want?

**Comment by sethtroisi** [comment]
more information in more recent threads: e.g. 
https://github.com/leela-zero/leela-zero/pull/1388
