### ISSUE TITLE
ISPC support for Winograd (4x4,3x3)?

### ISSUE THREAD

**Issue by roy7** [leela-zero/leela-zero#1722]
I mentioned some of our recent upgrades to the Leela Chess people, and something they did they suggested we look at is:

https://github.com/LeelaChessZero/lc0/pull/224

It would need updated/changed to support 4x4,3x3 but they said the vectorization speedup was substantial. This is lower level stuff than I have any knowledge of, but I wanted to pass this on to the appropriate powers that be like @ttl and @gcp.

**Comment by Ttl** [comment]
The transformations are not very well optimized in the CPU code at the moment so I wouldn't be surprised if there was performance improvement with good vectorization. However I don't think that I'm going to implement this. I'm not very interested in optimizing the CPU performance since I don't need it myself.

**Comment by roy7** [comment]
Totally understand. Just sharing interesting things I found on the Leela Chess side since I've been visiting the past few days in their Discord. :)

**Comment by gcp** [comment]
Seems like a very annoying dependency. Not all that interesting IMHO.

**Comment by sethtroisi** [comment]
closing older issue with no owner
