### ISSUE TITLE
Questions about FastBoard

### ISSUE THREAD

**Issue by barrybecker4** [leela-zero/leela-zero#173]
Thanks for contributing this project. It's really great.
I went through the FastBoard code today and have some questions. It would be great if you could add some comments directly to the code that would address these questions. I am sure that a few words of explanation will help others that might try to understand it.

What is the difference between count_pliberties and count_rliberties? Specifically, what to the "p" and "r" stand for?

What is the significance of 16384? m_libs[MAXSQ] is initialized to it. After some guessing I deduced that it is 2^14,  but why? Is this value the same regardless of the size of the board?

 Does m_libs hold the number of liberties of the parent string at each board position? 

 What does ss stand for in fast_ss_suicide?
 
 How does the s_eyemask work?

Instead of MAXSQ being used throughout the code, shouldn't you use m_maxsq? That way everything should work for dimensions other than 19x19. Maybe I'm wrong and it already does work for other dimensions.
 
How should we interpret the value that resides in m_neighbours[i]? I don't think it is literally the number of neighbours, but I'm not sure how it is used.
 
How does count_neighbours work? In particular can you add a comment to this line to explain what it does?
   ` return (m_neighbours[v] >> (NBR_SHIFT * c)) & 7;  `
			
In display_board, the code that draws the "a b c ..." letters at top and bottom is duplicated and could be refactored out into a separate method.  I'll make a pull request for this once I can build on windows.

Thanks!

**Comment by fishcu** [comment]
> What is the difference between count_pliberties and count_rliberties? Specifically, what to the "p" and "r" stand for?

I have not gone through the code in detail, but to make an educated guess, I would say these refer to "pseudo liberties" and "real" (?) liberties.
With pseudo liberties, you count all neighboring empty cells to a group as a liberty. When placing stones adjacent to that group, you add one pseudo liberty for neighboring empty cells, and you remove one pseudo liberty for each neighboring group. There may be duplicate pseudo liberties with certain "bent" shapes. However, the test for 0 liberties remains correct, and IIRC, there is also a simple "atari" check.
Real liberties, OTOH, correspond to actual liberties of the group. I have not checked the code but would assume they're implemented using union-find.

The difference is speed, pseudo liberties have O(1) adding and removal, and real liberties have the inverse Ackermann function for that, but in practice there is a significant speed difference.

**Comment by barrybecker4** [comment]
@fishcu, those seem like reasonable guesses, but I'm not so sure. I hope that @gcp will be able to verify one way or the other, and perhaps provide references to the relevant literature if applicable. I did a [port of the FastBoard class to scala](https://github.com/barrybecker4/leela-zero-scala) (in an attempt to understand it better) and added some unit tests which lead me to believe that pliberties are the number of liberties of the "point", and rliberties are the number of liberties of the parent "string". The number of rliberties for an EMPTY position seems to be 16376. 

For example, given
```
  a b c d e
5 . . O . .  5
4 X . O . .  4
3 . . O X .  3
2 . X X O .  2
1 . . . . .  1
  a b c d e
```
Then these tests pass:
```
  test("Count real liberties on 5x5") {
    val b = createFilled5x5Board()
    val vertices = Array(
      b.getVertex(1, 1), b.getVertex(2, 1), b.getVertex(3, 1), b.getVertex(4, 1), b.getVertex(2, 2), b.getVertex(3, 2), b.getVertex(0, 3)
    )
    assertResult("4, 4, 2, 16376, 5, 2, 3") {  
      vertices.map(v => b.countRealLiberties(v)).mkString(", ")
    }
  }

  test("Count empty neighbors on 5x5") {
    val b = createFilled5x5Board()
    val vertices = Array(
      b.getVertex(1, 1), b.getVertex(2, 1), b.getVertex(3, 1), b.getVertex(4, 1), b.getVertex(2, 2), b.getVertex(3, 2), b.getVertex(0, 3)
    )
    assertResult("3, 1, 2, 2, 1, 2, 3") {  // correct!
      vertices.map(v => b.countNeighbors(EMPTY, v)).mkString(", ")
    }
  }
```

**Comment by betterworld** [comment]
Look at the code in the comments in count_rliberties. This is just a simple implementation to find liberties of a (fully connected) group containing a given coordinate. I guess the code is in comments in order to make it easier to understand the actual code which uses the m_libs array, which is faster and equivalent to the code in the comments. m_libs is update in the add_neighbour function.

On the other hand, count_pliberties just counts the liberties of a single stone, ignoring if it is part of a group or not.

An empty point does not have a group so I guess you can think of 16384 as a dummy value like 0xdeadbeef.

**Comment by barrybecker4** [comment]
Another question: What is the purpose of s_cinvert? It does not seem to be used for anything anywhere. I think it can be removed.
See https://github.com/gcp/leela-zero/search?utf8=%E2%9C%93&q=s_cinvert&type=

**Comment by gcp** [comment]
>What is the difference between count_pliberties and count_rliberties? Specifically, what to the "p" and "r" stand for?

Pseudo and real liberties. The difference has been explained above.

>What is the significance of 16384? m_libs[MAXSQ] is initialized to it. After some guessing I deduced that it is 2^14, but why? Is this value the same regardless of the size of the board?

Random "infinitely" large value that fits in a short. It's used to signal that an empty square is never "in atari".

>Does m_libs hold the number of liberties of the parent string at each board position?

The question is phrased a bit weird. It's the number of liberties for the string of which the index is the "parent" vertex, and only guaranteed to be correct for that parent vertex.

But I think the answer to what you were intending to ask is most likely yes.

>What does ss stand for in fast_ss_suicide?

Single-stone.

>How does the s_eyemask work?

I guess it will be clear if I explain m_neighbours.

>Instead of MAXSQ being used throughout the code, shouldn't you use m_maxsq? 

Static arrays require the size to be known at compile time.

>How should we interpret the value that resides in m_neighbours[i]? I don't think it is literally the number of neighbours, but I'm not sure how it is used.

It's contains the count of the number of neighbours for each color+empty, packed into a single short. (But 'off the board' squares are considered to contain both color's stones - this is arbitrary but done because it helps checking liberties, atari, etc)

>return (m_neighbours[v] >> (NBR_SHIFT * c)) & 7;

BLACK = 0, WHITE = 1, EMPTY = 2, INVAL = 3
NBR_SHIFT = 4

m_neigbours looks like
```
0000 0000 0000
^ empty neighbours
          ^ white neighbours
                  ^ black neighbours
````

**Comment by barrybecker4** [comment]
Thanks for the answers. I hope to do a pull request to add some comments and other minor changes once I can build on windows (hopefully soon). 
It's been a long time since I used c++, but I thought that the arrays could be allocated at runtime when the board was constructed.  Having them statically allocated to MAXSQ means that it will only work for 19x19 or at least use more memory than needed if smaller size than that.
That is a clever trick to encode 3 three neighbor values into a single short. I wonder how much performance is gained for that added complexity. I guess it's worth it because it is on the critical path.
Probably s_cinvert can be removed. I don't think it is used.

**Comment by OmnipotentEntity** [comment]
Allocating the array at runtime requires an indirection (ie pointer dereference).  This is because the compiler must know the stack frame size at compile time to handle stack allocation.

The NN won't really be adaptable to other size boards so statically sizing the board isn't a really big loss.

That being said, I'm unsure how much a pointer indirection will actually cost due to aggressive caching in modern CPUs and CISC instruction sets (like x86) supporting memory addressing modes that include pointer dereferencing with offsets directly.  But if you don't need the flexibility, why risk the speed?
