### ISSUE TITLE
Colab had TPUs. How to use it

### ISSUE THREAD

**Issue by kennychenfs** [leela-zero/leela-zero#1918]
I found there were tpus on colab.
how to use it?

**Comment by alreadydone** [comment]
I don't think TPUs work with OpenCL, and it may be substantial effort to learn to program with TPU. How does that compare with programming with CUDA or with OpenCL?

**Comment by wonderingabout** [comment]
google colab is unreliable since a few weeks now, after 1-2 hours of game producing they'll disconnect your instance because use is non interactive, then you'll have to wait another time to get another instance...; for only a few hours, see their FAQ : 
https://research.google.com/colaboratory/faq.html#gpu-availability

if you want to help, you may rather want to try google cloud free trial that comes with a V100 (much faster than a tesla K80), see #1905

**Comment by DonMathi** [comment]
The script has started asking a question about the file system:
Configuration file '/etc/apt/sources.list.d/cuda.list'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.

**Comment by DonMathi** [comment]
Also: Now it fail to start: *ERROR*: No 'leelaz' binary found.

**Comment by kwccoin** [comment]
Mine as well

**Comment by kennychenfs** [comment]
Maybe the tpus is only for tensorflow, so we can't use it.
Then we can't use colab to train anymore.
I can't find colab's game on lc0, too.
Maybe we can't use it to play except python.

Kowloon walled city (coin) <notifications@github.com> 於 2018年10月15日 週一
下午2:38 寫道：

**Comment by sethtroisi** [comment]
TPUS are discussed in https://github.com/leela-zero/leela-zero/issues/1377 and in the minigo issue
