### ISSUE TITLE
a way to produce a smaller  network with the same "knowledge" as  big one

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#1924]
http://blog.lczero.org/2018/10/understanding-training-against-q-as.html#more

Understanding Training against Q as Knowledge Distillation.
Background
Knowledge Distillation (KD) [1 , 2] is a technique where there are two neural networks at play: a teacher network and a student network. The teacher network is usually a fixed, fully-trained network, perhaps of bigger size than the student network. Through KD, the goal is usually to produce a smaller student network than the teacher -- which allows for faster inference -- while still encoding the same "knowledge" within the network; the teacher teaches its knowledge to the student. When training the student network, instead of training with the dataset labels as targets (in our case this is the policy distribution and the value output), the student is trained to match the outputs of the teacher.

**Comment by gcp** [comment]
Nice that the KD training technique works.

If I understand the reasoning, KD works effectively because you don't try to teach the smaller network things which even the larger network can't fully comprehend (i.e. values that even the larger network doesn't "learn" properly...for example because they're wrong or too tactical).

The leap to say that this relates to training against the MCTS output instead of game result I'm not so sure about. Using the search result as a training target instead of self-play outcomes is in itself an older technique predating AG(Z) by many years.

As usual, it wouldn't hurt testing.

>When bootstrapping a new network, we can use a strong network from a previous run, such as ID 11248 or the latest test20 networks, as teacher at a high LR to get a decent network very quickly.

This is more or less what we observed with ELF.

**Comment by sethtroisi** [comment]
closing old suggestion with no owner or update.

side note minigo looking briefly into this reach out to me if anyone starts on this
