### ISSUE TITLE
I have question about using different type of gpu at the same time

### ISSUE THREAD

**Issue by sewim** [leela-zero/leela-zero#2051]
Recently I bought Titan V and added on my original system(GTX 1080Ti x2 / windows 10 pro)
So, Basically now It has 3gpu(gpu0=Titan V, gpu1=GTX 1080Ti, gpu2=GTX 1080Ti  / windows 10 pro)

After I added 1 more gpu, There is significantly slow down in loading process when I open lizzie or attach engine on sabaki(almost spending over x2 times)
Anyway I think that is normal and fixed it by adjusting some option.
But, Useage gpu status also very low almost 12-18% per each devices.
(When I tried with only GTX1080Ti x2, It was 20-30% per each devices)

Are there theorical possiablities to be low performenced output when I am using different type of gpu at the same time? or Did I misunderstand something about useage gpu status?

Thanks.

**Comment by alreadydone** [comment]
Long loading time may be caused by precision autodetection. Did you solve it by specifying --precision half? 
You may need more threads to saturate more GPUs. You may also want to try out my https://github.com/alreadydone/lz/tree/fastexit-tensor+ branch, which incorporates my work to use threads more efficiently (simulation threads no longer need to wait for GPUs to return the results) and ihavnoid and bood's work on batching and tensor core utilization. Tuning needs to be re-done to use it though.

**Comment by alreadydone** [comment]
People pursuing ultimate speed (especially with multiple GPUs) prefer Linux to Windows due to smaller overhead and/or unlimited number of calls per time period IIRC. However some reported that with my recent branches the speed difference between Linux and Windows becomes negligible, possibly due to more efficient use of threads and batching which makes the number of OpenCL calls smaller.

**Comment by sewim** [comment]
> Long loading time may be caused by precision autodetection. Did you solve it by specifying --precision half?
> You may need more threads to saturate more GPUs. You may also want to try out my https://github.com/alreadydone/lz/tree/fastexit-tensor+ branch, which incorporates my work to use threads more efficiently (simulation threads no longer need to wait for GPUs to return the results) and ihavnoid and bood's work on batching and tensor core utilization. Tuning needs to be re-done to use it though.

1. Yes I used --precision option.
2. Unfortunately I don't have technical abilities at all... I am willing to offer my resources as a testbed.

**Comment by alreadydone** [comment]
I now have someone helping me testing on a 1080Ti x 8 + Titan V x 2 machine. I can make an .exe release of my branch after fixing some bugs.

**Comment by pliuphys** [comment]
> People pursuing ultimate speed (especially with multiple GPUs) prefer Linux to Windows due to smaller overhead and/or unlimited number of calls per time period IIRC. However some reported that with my recent branches the speed difference between Linux and Windows becomes negligible, possibly due to more efficient use of threads and batching which makes OpenCL calls less frequent.

What's the performance gap for 0.16?

**Comment by sethtroisi** [comment]
closing old issue with no action items and no discussion for 2 months.
