### ISSUE TITLE
why lz204 didnt resign when a doze of stone were captured

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#2215]
it played pass instread
http://zero.sjeng.org/viewmatch/3297416bbcdcf2822bf35dd0bf22449aabe87f7a5c073ca1b055ee9eb49cde6c.sgf

**Comment by Vandertic** [comment]
Actually, there is something really weird in that game. Black did not pass. Black stopped playing and last 11 moves in sgf are white's. In fact the game finished because of two consecutive passes of white.

...B[cs];W[ap];B[ir];W[hq];B[jq];W[gp];W[jr];W[eq];W[gr];W[fp];W[ep];W[in];W[tt];W[im];W[tt];W[tt])
