### ISSUE TITLE
Disabling pruning in self-plays

### ISSUE THREAD

**Issue by Vandertic** [leela-zero/leela-zero#2264]
https://github.com/leela-zero/leela-zero/blob/63af3687462ba27daeabc526da6bbfa3d6149389/src/UCTSearch.cpp#L639

While debugging SAI I noticed something in LZ code that may or may not be a bug. (I don't know if I am not understanding the code well here.)

When not pruning (for example because the game is self-play and '-n' was given), `prune == false`, but `pruned > 0` anyway, because of how `prune_noncontenders()` is written.

In fact when I try a game locally it never does the number of visits required. 

Branch master, command
`./leelaz -w ../../LZ207.gz -t1 --noponder -p0 -v1600 --precision single -n`

![image](https://user-images.githubusercontent.com/27057329/53698272-9bf1f100-3dda-11e9-9688-bd489f35d3a7.png)

What am I missing? Thank you.

**Comment by Hersmunch** [comment]
See #1497 and #1416.

**Comment by Vandertic** [comment]
Thank you @Hersmunch. I missed the moment when this change was introduced.

**Comment by Ishinoshita** [comment]
This type of behaviour speeds up the self-play games but interfere with policy training. In a position where the policy prior tends to put much weight on a single move, cutting the search because most visited child cannot change will reinforce that single move probability in the policy.

Same applies for noise driven exploration. If a move pushed by d-noise turns out to be 'not so bad', search should reinforce it. Cutting the search may prevent this reinforcement. Initial tree growth is driven by policy prior. Good / not so bad moves will eventually partly catch up mostly in the end of the search. 

MCTS with its (inevitably) limited playouts budget tends to create some sort of local minima for the policy, as current UCB formula put some threshold for a move policy to yield at least one visit. This naturally sharpen the policy. Cutting the search just reinforce this. Possibly. Just MHO though.
