### ISSUE TITLE
Double-passing pathology

### ISSUE THREAD

**Issue by gjm11** [leela-zero/leela-zero#2273]
Consider the following situation, which might arise anywhere in the search tree.

* Black is far ahead, perhaps because this is a handicap game.
* However, if the game ended here then the end-of-game scorer LZ uses would reckon it a win for white (e.g., because neither side has any territory yet and W has komi).
* The NN's policy head gives non-negligible weight to passing for whoever's move it is in this position. (Even though passing is actually a dumb idea.)
* It's white's move.

Then when MCTS visits this position, quite early in the search it may look at the line where W passes and then B passes -- which will be assessed as a win for _white_. After that, until this position has been visited many many more times, B's winrate here will look anomalously low.

In the long run, this is harmless. But the long run may be very long. E.g., if "normal" play yields a 99.5% winrate for black, then passing in this position is going to look like a good move for white until the position's seen about 200 visits. And if some of the positions further down the tree _also_ evoke non-negligible weight on passing from the policy head, it may be a whole lot more than 200 visits.

This hurts us (1) if passing is one of W's options from the root position, in which case it may get chosen because of this effect even though it's a silly move, and (2) in any position where this sort of thing occurs _somewhere_ in the tree, because then every position's evaluation gets some admixture of nonsense double-pass-and-win outcomes.

For an example, try putting 6 handicap stones on the board and letting white think for a while using Lizzie. Here is what you will see, or at least what I see using network 208, which is the latest right now. (Of course the details may vary depending on the order in which you place those handicap stones, and what orientation LZ happens to feed the board to the NN in.)

* Initially, LZ wants to play either a 3-3 invasion or a knight's-move approach. For the first ~5k visits, these moves are clear winners. Every move, though, has a black winrate in the 97%-99.5% range or thereabouts; typically LZ prefers a move whose winrate is ~97%.
* Every now and then, though, some (typically crazy) move will get considered and will be seen as having a much lower black winrate: maybe 80% or so. As LZ searches it more, that winrate will gradually climb up until it's in the same range as all the other moves' winrates, and then it will switch to a different move.
* Eventually (after ~5k to 15k visits) it will stumble across a move on the edge of the board whose B winrate starts off a little under 2/3 and climbs a bit more slowly; this becomes LZ's preferred move for some time.
* After longer still (maybe 15-30k visits), it will find that a move _in the corner_ (say, A1) has a B winrate that starts at ~2/3 and climbs even slower. It will take some time for that move to become the favourite, but once it does it will remain the favourite for quite a long time.
* After that, I lost patience at maybe 45k visits or so. (My computer's GPU is not very fast.) Maybe LZ eventually gets back to more sensible moves, maybe not.

What's going on here? Those crazy moves with low B winrates are ones where the pathology I describe above happens. I think the ones whose winrate climbs slower are ones where the same pathology occurs more frequently in the tree. But take note, also, of the rather frequent 97-98% winrates: I think those too are a consequence of the pathology.

If we repeat the experiment with a version of LZ whose searching code has been tweaked to prevent this pathology (and, if I did it right, to change nothing else) then instead we find:

* Initially _every_ move has a winrate on the order of 99.5%.
* None of those sporadic <<99% moves occur.
* LZ prefers "sensible" moves -- 3-3 invasions and keima approaches -- for as long as I let it search for.

Here is the change I made, in UCTNode.cpp near line 100. (I make no claim that this is the best change to make or the best way to make it.)

	// Hack: if "parent" move in search tree was a pass
	// and NN eval of this position is very good, check whether
	// a second pass here would lose; if so, don't consider a pass
	// here if there are any other legal moves.
	// Note: m_net_eval and final_score() are always from B's point of view
	if (state.get_passes() == 0
		|| (state.board.white_to_move() ? 1.0f - m_net_eval : m_net_eval) < 0.75
		|| (state.board.white_to_move() ? -state.final_score() : state.final_score()) > 0) {
		nodelist.emplace_back(raw_netlist.policy_pass, FastBoard::PASS);
	}

I would expect the speed impact of this change to be negligible, but haven't performed careful experiments.

It looks to me as if making some change along these lines is a clear improvement -- but I am not an expert on the LZ codebase and it is entirely possible that there are subtleties I am missing.

Making this change doesn't eliminate all passing-related pathologies. If the NN genuinely prefers the position after passing to the position before passing, LZ will still pass (though in some cases the sanity check that's already there will prevent that on the grounds that it loses immediately). But it seems like it eliminates one major failure mode that in some positions not only directly causes spurious passes and crazy moves (A1!) but also perturbs LZ's evaluation (and hence its relative ordering) of sensible moves.

**Comment by l1t1** [comment]
the brief version?

**Comment by Vandertic** [comment]
I confirm the pathology exists, in particular with handicap stones. Since one of SAI's aim is to play handicap go, we noticed it some time ago and made a similar patch on SAI code.

**Comment by petgo3** [comment]
@gjm11: Thank you for this hint. IMO it helps a lot with handicap games. In H4 games leela behaves a lot more reasonable.

**Comment by mylyu** [comment]
Thanks for finding this problem. Yet I agree that for such long discussion, a concise overview in the beginning will greatly improve the readability. So in short, you find that in handicap games, the possibility of double passes in the policy tree can cause win rate illusions on strange moves. Right?

**Comment by gjm11** [comment]
Not necessarily only in handicap games, but that's the most likely place where it matters. Not necessarily only on strange moves, but strange moves are likely worst affected (because they produce the most unusual positions, hence ones in which NN policy is most likely to make bad proposals).

**Comment by lightvector** [comment]
Out of curiosity - to what degree do the MiniGo converted Squeeze-Excite weights suffer from the same problem without using this fix? Certainly much of the difficulty is going to be from the fact that such extreme positions are not present in the training data, but part of also why generalization to such positions could be poor is because computing where you should pass or not is a very global operation. You want to globally know whether there are unfinished borders, and whether you will win or not given what borders are unfinished or not, as well as whether the opponent has passed or not (which also involves looking globally at the history planes to check that there are no diffs from the current state).

But the AlphaZero architecture is fully convolutional up to the very last layer in the policy head, where it is *linear*, and that's it. Convolution should have a hard time summing the several relevant global statistics mentioned above in a uniform way across the board, requiring a massive number of layers to coordinate, and then you smash it down to only 2 channels, and then your only operation that actually naturally gets information from the whole board is linear, so you don't even allow for any complex processing of the globally-combined values.

There's a chance that the Squeeze-Excite architecture used by MiniGo (or any other architecture with a global pooling mechanism) generalizes better in this case, because the presence of global information aggregation much earlier in the neural net should make it easier to compute properties like this when convolutions cannot. So how the MiniGo architecture behaves would be interestingly indicative of whether this is primarily a lack-of-training-data problem, or also that the architecture itself contributes to difficulty of generalization.

**Comment by gjm11** [comment]
In #2275, GCP suggests that if we have a fix like this then it should be disabled when "dumbpass" is turned on. I think we shouldn't, because this is causing misevaluation of positions as well as actual unwise passes. (Perhaps it should be disabled when "dumbpass" is on _and we're at the root of the search tree_, but I'm not convinced even by that.)

**Comment by gjm11** [comment]
Incidentally, the code above is not quite right; the accumulation into `legal_sum` also needs to be conditional on whatever conditions we impose on adding passing to the nodelist.

**Comment by gcp** [comment]
The whole point of dumbpass is that it disables any "smartness" in how passing is handled. Whether you want to try to argue this is about evaluation or anything else is completely irrelevant there.

Note that dumbpass isn't even the default in analysis and gameplay.

**Comment by amj** [comment]
@lightvector Minigo v17 seems to be fine at knowing when to pass?  I'm not sure about the pathology here.  Here's a resign-disabled game https://cloudygo.com/v17-19x19/001003-leviathan/full/1551156169-tpu-player-job-nr-dccbl-3.sgf?type=full , and this pass behavior appears 'correct' to me.

It's difficult to talk about correct behavior; a losing 'bot should never agree that the game is over, because a final Q=0 is worse than an infinitesimal one.  So the only way a bot will pass-if-losing is if the pass prior was very, very high.

@lightvector  Do you have a set of positions where this 'pass behavior' happens that i could test for you?

**Comment by lightvector** [comment]
@amj - If you skim the top post by gjm11, it's about an issue where in extremely unbalanced opening positions, such as in the starting position of a 6-stone handicap game, the search tree will contain a few percent of nodes where *black* mistakenly passes. But despite black being far ahead, no territory is actually enclosed, so white will pass in response and win by Tromp-Taylor rules due to 7.5 komi. Although only a few percent of nodes deep within the tree, this is enough to make the winrate bounce around between 97-99% and cause LZ after thousands to tens of thousands of playouts to eventually sometimes favor moves on the first line, since those first-line moves anomalously get (or even cause) more mistaken black passes deeper in the search tree after that.

So likely LZ's policy is assigning too high a weight to black passing, causing bad search behavior, causing white to make stupid first-line moves in 6-stone handicap games. If you fix this with gjm's manual hack, then white stabilizes and makes reasonable moves (although of course still believing itself to be hopelessly lost).

I'm wondering if Minigo v17 as well as earlier versions of Minigo pre-SE exhibit this behavior. When run for tens of thousands of visits on the starting position of a 6-stone handicap game, does white make reasonable moves? Does the neural net generalize sensibly from its training to the very unusual far-from-training position of a 6-stone handicap game?

**Comment by gcp** [comment]
Should be fixed in non-Zero mode now.
