### ISSUE TITLE
Microsoft Azure Free Trial Script

### ISSUE THREAD

**Issue by ozymandias8** [leela-zero/leela-zero#2333]
I started running the Google Cloud Tesla v100 and wanted to do the same with Azure. The problem is that Azure uses Ubuntu 16.04, which doesn't have the latest compilers by default (gcc-8). These are apparently required to compile the newest leela-zero release 0.17. See [#2303](https://github.com/leela-zero/leela-zero/issues/2303#issue-425379717)

I've managed to get the compilers installed on my node using the following code.

`/bin/bash -c 'sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update && sudo apt-get -y install gcc-8 g++-8'`

Unfortunately I'm just a Go player trying to help out, not really a programmer or Linux power user. I can't figure out how to reassign Ubuntu to use the new compiler as the default, and my leela-zero script from the guide still won't compile as a result. From googling it seems like I need to use CMAKE, but so far no luck getting it to work. Apparently it can only be run from inside a particular folder on the node?

Any help is appreciated.

**Comment by Splee99** [comment]
I'm wondering why you can't use the windows virtual machine on azure for this.

**Comment by ozymandias8** [comment]
I don't know, I was following the guide that @wonderingabout wrote. I could try to set it up some other way, but I have no idea what I'm doing. I guess I'll try to go in there and poke about, see if I can come up with anything.

**Comment by wonderingabout** [comment]
@ozymandias8 @Splee99 

its been long since i last looked at this, but thanks for your interest :+1: 

i didnt know about windows virtual machine option, do they cost more dollars per hour ? (on google cloud linux cloud is cheaper than windows cloud due to licensing fees)

also, the advantage of the linux tutorial is that the instances auto delete and recreate themselves using preemptible costs, but i doubt the windows virtual machines are automated nor are using preemtpible prices (low priority costs)

finally for gcc there wasnt such an issue with lz 0.16 indeed, but if its really needed, then using the ppa may be an option, try it and if it works i can update the tutorial :+1:

**Comment by ozymandias8** [comment]
@Splee99 I looked it up, and it seems the windows VM with NC6s_v3 nodes are something like 5 times more expensive than the Linux preemptible nodes, which is a massive difference. That being said, I did manage to get it working on Linux!

@wonderingabout ~~any idea how to change the default to gcc-8 after I SSH into the node? I'm a Linux noob and so far I'm not having much luck.~~

Edit: Got it! Apparently one of the many commands I tried actually worked. I think you need to do the following:

1) install the new gcc from the ppa or through SSH. Not 100% sure if this code is perfect.

`/bin/bash -c 'sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update && sudo apt-get -y install gcc-8 g++-8'`

2) At this point I was stumped so I used Putty to SSH into the node. From the node screen you go to "Connect" and create a remote user access then simply Putty in. Now that we're in, we can set gcc-8 to the default using update-alternatives:

`sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 40 --slave /usr/bin/g++ g++ /usr/bin/g++-8`

At this point I got a message stating "using /usr/bin/gcc-8 to provide /usr/bin/gcc (gcc) in auto mode"

3) I verified that gcc-8 was the default by:

`gcc --version`

4) I created a job schedule using the script by @wonderingabout [#1905](https://github.com/leela-zero/leela-zero/issues/1905#issue-366048983):

`/bin/bash -c 'sudo -i ; sudo apt-get -y install clinfo ; rm -r leela-zero ; clinfo ; nvidia-smi ; git clone https://github.com/leela-zero/leela-zero && cd leela-zero && git submodule update --init --recursive && mkdir build && cd build && cmake .. && cmake --build . && cd ../autogtp && cp ../build/autogtp/autogtp . && cp ../build/leelaz . && ./autogtp -g 2'`

Examining the stdout file shows that we are now making games, lots and lots of games. Huzzah! Between Google, Microsoft Azure, and my local machine I must be doing almost 2k games/day.

**Comment by wonderingabout** [comment]
great @ozymandias8 ! :100: 

big thanks for the feedback

what i liked in azure is the ability to do it all in web browser, and since my old azure instructions didnt need SSH, i'd like to keep it as is, so i think just install gcc-8 with startup script should do the script, which should be, based on your instructions : 

`
/bin/bash -c 'sudo -i ; sudo apt-get -y install clinfo ; rm -r leela-zero ; clinfo ; nvidia-smi ; sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test ; sudo apt-get update ; sudo apt-get -y install gcc-8 g++-8 ; sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 40 --slave /usr/bin/g++ g++ /usr/bin/g++-8 ; git clone https://github.com/leela-zero/leela-zero && cd leela-zero && git submodule update --init --recursive && mkdir build && cd build && cmake .. && cmake --build . && cd ../autogtp && cp ../build/autogtp/autogtp . && cp ../build/leelaz . && ./autogtp -g 2'
`

can you create a new virtual machine using only this script (and no SSH thing) @ozymandias8 

big big thanks :1st_place_medal: 

edit : note for myself later, then i'll need to also update google cloud instructions as well :+1:

**Comment by ozymandias8** [comment]
I am pretty busy today but I'll get back to you soon.

Edit: @wonderingabout  I just ran your script above on a fresh node and it worked perfectly. Looks like you can update your guide.

**Comment by wonderingabout** [comment]
ok !

i'll update the tutorial soon too :+1: 

thanks again for all the effort :+1:

**Comment by wonderingabout** [comment]
ok ! @ozymandias8

i'll update the tutorial soon too :+1: 

thanks again for all the effort :+1:

**Comment by wonderingabout** [comment]
just updated the azure tutorial : https://docs.google.com/document/d/1DMpi16Aq9yXXvGj0OOw7jbd7k2A9LHDUDxxWPNHIRPQ/edit

just updated the google cloud tutorial : 
https://docs.google.com/document/d/1P_c-RbeLKjv1umc4rMEgvIVrUUZSeY0WAtYHjaxjD64/edit#

this thread is a linked with #1905
