### ISSUE TITLE
it seems other opening pattern has better winrate vs lz220

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#2338]
http://www.yss-aya.com/cgos/19x19/cross/LZ_220_t10_p3200.html
I checked the games lz lost to HE608, int those games HE608 always played 3-3 or 3-4 at opening moves

**Comment by l1t1** [comment]
from https://lifein19x19.com/viewtopic.php?p=242818#p242818
ELFv2 win games also  played 3-3 or 3-4 at opening moves

**Comment by ozymandias8** [comment]
Yes, but doesn't AlphaZero nearly always open with star point openings? I seem to recall a lot of games like that reviewed by Michael Redmond 9p. 

Also, CGOS is not a great comparison because people run on all sorts of hardware. For example "Black Hole" bot has a super strange opening that is objectively bad and yet it still beats everything, likely because it's running on beefy hardware.

Still, I feel like none of this matters. Human pros believe it's impossible to know what opening is "the best" in a game as complex as Go, but who knows.

**Comment by MartinVingerhoets** [comment]
You are saying that "it seems other opening pattern has better winrate vs lz220". Could you explain to us how you came to this conclusion? What do you mean with "other opening pattern", since the opening is not decided by one player but by both players choosing their own moves? Can you explain why Leela-Zero loses more often due to the opening and not due to other factors since you are comparing different networks with each other? How do you think we can solve this problem, if it is a problem at all?

**Comment by Splee99** [comment]
Golaxy always starts with 3∼3.  Binary_star always starts with those weird center moves. How did they train such network?

**Comment by ozymandias8** [comment]
Wild speculation here, but I would be willing to bet Black Hole is Leela Zero or similar engine with the first four moves manually fixed. Something like that anyway.

**Comment by iopq** [comment]
Can some one test the winrate of the black hole opening at visit parity?
