### ISSUE TITLE
winrate and komi

### ISSUE THREAD

**Issue by salusijf** [leela-zero/leela-zero#2384]
HI,

I don’t understand why the win rate is still the same whatever the value of the Komi.
For the first move with LZ network (#225) : 
-	with Komi = 7 .5 : WR = 43.6
-	with Komi =    0 : WR = 43.6

**Comment by wpstmxhs** [comment]
Winrate is from output of neural network's value head.
But neural network doesn't have a input for komi.
Therefore, regardless of GTP komi settings, winrate is calculated based on komi of 7.5 points.
Because weights are trained from komi 7.5 self-play games and value head output is estimation of its game result.

Simply speaking, you can't change komi from 7.5 points.

**Comment by salusijf** [comment]
Ok, thanks for the answer.
