### ISSUE TITLE
Batching has less than 40% win ratio vs. no batching/threading

### ISSUE THREAD

**Issue by iopq** [leela-zero/leela-zero#2403]
I did a short match, so the results are not conclusive, but it confirms that batching results in a large loss of strength at preset visits.

See https://github.com/leela-zero/leela-zero/pull/2253

Any plans to do batching multiple games together instead? It should result in stronger self-play games

**Comment by wonderingabout** [comment]
if that is documented and confirmed (that batch size significantly hinders strength), then it seems wise to disable it for selfplay and make only an option for match games (or even less, only outside of autogtp)

**Comment by Ttl** [comment]
Batching is weaker per node, but it can evaluate NN faster so that it's stronger with equal time. Self-play games could be batched across games, but that would require significant amount of work. At least I'm not going to work on that.

Self-play games with batch size 1 are stronger, but the evaluation speed is half of the current settings. If self-play game strength is a problem doubling the nodes would result in stronger data with the same computational effort as batch size 1.

**Comment by wonderingabout** [comment]
but in other words, selfplay games batchsize 1 -v 1600 would be significantly stronger than selfplay games batchsize x -v 1600 (regardless of time needed per game)

**Comment by ghost** [comment]
If I understand @Ttl correctly, it's better to adjust the -v parameter up from 1600 to a higher number rather than lower the batch size, assuming that selfplay strength is to be increased.
