### ISSUE TITLE
Freeze opening moves when self-play

### ISSUE THREAD

**Issue by KhiemDuyNguyen** [leela-zero/leela-zero#2442]
Is there anyway to do it?

**Comment by Friday9i** [comment]
Could you precise your question? What you mean with "selfplay" is quite unclear...
If you mean autogtp, it's not possible.
If you mean when playing against LZ or doing a match between LZ and another engine, then it's possible (eg Lizzie for selecting the moves played by LZ, or Gogui to organise matches between engines with one or several forced openings)

**Comment by KhiemDuyNguyen** [comment]
@Friday9i Thank you for the reply.
Right now we generate games (with smaller board-size) using validation in leelazero, let it plays with itself (same weight). We want to observe the result when it makes different opening moves.
I hear a guy have done it on 9x9, but he never reply my pm on his git.

**Comment by iopq** [comment]
https://www.mankier.com/1/gogui-twogtp use this script to do it

**Comment by Friday9i** [comment]
I'm using Gogui too, and it can use selected opening(s): you create a folder with the opening(s) and the engines are playing these openings (one after the other if there are several openings).
On my side, I mainly compare the strength of different LZ nets and the strength of other engines (eg Elf, KataGo), cf for example https://github.com/leela-zero/leela-zero/issues/2425 
For the openings, I created a panel of 200 very short 2-moves openings, and I use it in the matches to compare the engines. Cf https://github.com/leela-zero/leela-zero/issues/2104 (in the last message, I posted the 200 openings)

**PS:** when using openings to compare engines, I of course use the alternate option, so that both engines play each opening twice, once with Black, once with White, for evident fairness. 
**Note:** Gogui has a small but annoying bug with alternate. In even games, the sgf is correct but in odd games, the engines indicated in the game properties are not inverted (eg if in properties of odd game 3, you see Katago black and LZ white, it is in fact the opposite). Results in the html summary file are correct.

**Comment by KhiemDuyNguyen** [comment]
Thank you so much guys. I will experiment on it and see what I can do.

**Comment by KhiemDuyNguyen** [comment]
@Friday9i @iopq Do you guys use windows or Ubuntu? I use gogui with Ubuntu but it just keeps show error "The Go program terminated unexpectedly".

**Comment by Friday9i** [comment]
@Khiem I just noticed your question...: I'm using Windows. Did you manage to use Gogui eventually?
