### ISSUE TITLE
test match should pass at 400 and more games, but failed in the end

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#2535]
2019-11-10 14:51	a4b58a91   VS  0d2694c5  230 : 192 (54.50%)	422 / 400	fail

http://zero.sjeng.org/match-games/5dc815cf67c3c3343650b6e7 shows

400	55.00%	a48125d1e06ca06dc8abbdb953a3dad2	0d2694c5	W+Resign	163	0.9 minutes	sgf	10	18
401	54.86%	682a9268ad97394046c1657d381f779e	0d2694c5	B+Resign	146	1.0 minutes	sgf	5	18
402	54.73%	0224673cf1bafff4b88d69fc0e1783a7	0d2694c5	W+Resign	201	1.6 minutes	sgf	21	18
403	54.84%	802510d72d8c9c15d9a44c0855c31a1e	a4b58a91	W+Resign	237	1.0 minutes	sgf	1	18
404	54.95%	4cbf626b48e78798b1eb668dea20deda	a4b58a91	W+Resign	181	1.5 minutes	sgf	23	18
405	55.06%	5400201014816b30195407b4a3a0ca53	a4b58a91	W+Resign	173	1.3 minutes	sgf	8	18
406	54.93%	4e7b4a4761936fc34344611f48993b12	0d2694c5	B+Resign	278	2.2 minutes	sgf	20	18
407	54.79%	23529d5195dbba15ed00825489771bd1	0d2694c5	W+Resign	197	1.9 minutes	sgf	28	18
408	54.90%	c0d19ae0a4068d61db4f41822788d1dc	a4b58a91	B+Resign	224	2.1 minutes	sgf	25	18
409	55.01%	17fc9ed9dd3b1849a2b98961879d4bda	a4b58a91	W+Resign	169	1.5 minutes	sgf	28	18
410	55.12%	2074ccedd1c04de2db585636a5ba937c	a4b58a91	B+Resign	166	1.4 minutes	sgf	2	18

**Comment by roy7** [comment]
Test matches never promote, and this was a test between two 15b networks. If it ended up past 55% it might say "PASS" in the history log, but I think only real matches (not tests) will say PASS below 55% if the network promoted, since the way it knows it passed is because it's in the promoted list on left.

I guess someone could improve the front end when calculating the numbers to try and make the PASS sticky even on tests, but it doesn't have any real effect since tests don't change the current best network or the ELO scores.
