### ISSUE TITLE
Use games with several previous networks to estimate the Elo rating

### ISSUE THREAD

**Issue by eterevsky** [leela-zero/leela-zero#354]
Judging by the game counts at <http://zero.sjeng.org/>, Elo rating of the new networks are calculated mostly from the winning percentage against the previous ones. This is not very precise, since the networks may be overfitted to play against the previous versions, on the games from which they are trained. It would be better to play against several previous networks to estimate the ratings with higher confidence. It's also possible to update the ratings of the older networks using the games with the newer ones.

**Comment by roy7** [comment]
Accurate ELO isn't important to the project though since we aren't comparing those numbers to anyone else. (Granted lots of people compare them to AlphaGo Zero's paper, but they aren't truly comparable.) We only use the ELO graph as away to judge LZ's strength against itself over time, and to see the relative size of the jumps (bigger margin of victory, bigger increase on the chart).

**Comment by WhiteHalmos** [comment]
The community can come up with more accurate ELO anchors by testing against other bots. This project is to reproduce AlphaGo Zero's results in an open way, and AlphaGo Zero only tested the latest network against the previous best.

**Comment by sethtroisi** [comment]
Discussed more in depth in other threads
