### ISSUE TITLE
Different ELO level

### ISSUE THREAD

**Issue by olbrichj** [leela-zero/leela-zero#45]
Hey,
this is really great, and as soon as there is a distributable I will donate some time on my machine.

Do you consider to store the weights for different ELO level on you server? This way, we wouldn't just have an amazing AI to work with, but could kinda generate a teaching tool. Having a player slightly better then you, might help you improve faster than playing against SUPER-OVERPOWERED-AI :)

**Comment by marcocalignano** [comment]
A tournament between networks can also be distributed modifying a bit the autogtp application

**Comment by lane-westlund** [comment]
As an additional thought: I saw one ranking graph that included the strength of just the raw alpha-go-zero network.  It was (to me) also surprisingly strong.  It might also be a good idea to snapshot a couple of these weights at specific strengths, as I'd imagine these would be more useful on resource contained devices.

**Comment by gcp** [comment]
The networks will all be listed here: http://zero-test.sjeng.org/networks/ 
This is linked to the server DB that sends out the best one so far. So there will be a recording of every "epoch".

For playing games between networks you can use any GTP interface, as Leela Zero is GTP compatible. I use the "ringmaster" tool from "gomill" (a Python package) for this.

I don't expect evaluating the networks to be a bottleneck.

**Comment by gcp** [comment]
I have no idea how to even measure this. IIRC GnuGo is like a few hundred Elo on their rating scale, and GnuGo beast the current networks probably 100% of the time. So how can you calculate an Elo off of that?

If they had actually published any of their data, this would be easy...but then we wouldn't need to do this effort either.

**Comment by grolich** [comment]
In the AlphaGo Zero paper, where they show the Elo scale progression, the network starts at -3500.
Since it's the very beginning of the training (pre-training), and is (I assume) also starting from random weights, it seems unlikely that it would be that much different from leela zero's initial random state.

While the 20 block network is likely to have a lot higher potential than starter LeelaZ, I don't think it is too likely that anything far from LeelaZ elo is common enough in the search space to just be the initial random state of AGZ... 

But then again, "not too far" isn't a quantitatively useful measure... So we don't really know.

@gcp chose to start on a different scale, which is also fine. 
At any point he, or anyone else for that matter, can rebase that to whatever start elo we want to call the initial "random" state.

That said, As we start getting better results, it might be more convenient for people to see approximately how close/far we are from AGZ, but it definitely seems to not be an issue.

I would personally have thought it preferable to start on a similar scale (or definitely not a higher one) but it's not an issue at all since as stated, it can always be rebased to whatever is chosen.

**Comment by sethtroisi** [comment]
closing very old issue with no clear owner
