### ISSUE TITLE
Sophisticated game end condition

### ISSUE THREAD

**Issue by TFiFiE** [leela-zero/leela-zero#670]
Would ending the game early whenever one side has gained enough "pass-alive" territory (for a total of at least 184.5 points) lead to a significant speedup, at least when adjudicating self-play games and matches (if it would slow down the search too much)? It's not a heuristic and it would not likely be the cause of any bad habits.
Specifically, I'd like to refer to Erik van der Werf's work on extending Benson's algorithm.

**Comment by gcp** [comment]
I don't see what it would gain over resignation.

**Comment by Cabu** [comment]
What would be the reaction of that with a high handicap game (eg: 9 stones handicap). Would Leela abandon even before playing its first move? A 10kyu player can 'easily' make Leela abandon a game at 5 stones handicap.

**Comment by lightvector** [comment]
@gcp It would gain over resignation because a certain percent of the games have resignation disabled, and it could probably still be safely used in those.

It would also be additional complexity with some second-order effects on the distribution of training data, and the speedup would not be *that* large, which makes it less attractive to put effort into.

**Comment by OmnipotentEntity** [comment]
If you view some of the games where resignation has been disabled you'd realize that LeelaZero has some basic things to learn about large groups that it couldn't learn previously due to smaller nets.  Thus, at least for self play and training, it's important to force her into situations that she wouldn't normally see.

**Comment by jjoshua2** [comment]
What if half of the games that had resignation disabled use a resign setting of .01? This is an enormous efficiency increase over no resign, but still much less errors than the .10 setting normally used. And it would still retain some games to the bitter end for training.

**Comment by jkiliani** [comment]
@WhiteHalmos made many tests about the frequency of false resignations, including at very low threshold: https://github.com/gcp/leela-zero/issues/971#issuecomment-371309314

Even at extremely low thresholds, false resignations occur sometimes. To measure how games turn out when they go to counting, you have to enforce that for some of the games at least. Some late game self-ataris may happen when the losing side wouldn't have a chance anymore with normal play after all. It is also likely important that some late endgames are part of the training data, or the neural networks would eventually forget how to play these correctly.

**Comment by sethtroisi** [comment]
No active discussion for >10 months, closing
