### ISSUE TITLE
Validation won't stop with 0 wins or losses

### ISSUE THREAD

**Issue by roy7** [leela-zero/leela-zero#731]
Hey @marcocalignano, validation seems to run forever if wins or losses is 0 since it just shows:

> Status: 0 LLR 0 Lower Bound 0 Upper Bound 0

The way I handle that on server is use max(wins,1) and max(losses,1) for wins and losses in the calculation. Gives a conservative response for every request even if one or both numbers are 0.

Feature request. Allow validation to take -p and -v and pass the through to leelaz, with -p 1600 the default if neither specified?

**Comment by marcocalignano** [comment]
@roy7 When I first committed the SPRT feature I initialized the SPRT object with 1 win, 1 loss and 1 draw. So it could be always calculated. Was contested that this would falsify the result and was removed from the code. How can you say that your way (using max(wins,1)) does not falsify the result?

**Comment by marcocalignano** [comment]
@roy7 The others option are all implemented in the branch in my repository named /bin_option .
With that branch you can pass all the option you want to leelaz and you can choose even two different binaries. 
If you test it and it works just let me know so I can rebase and make a PR.

**Comment by roy7** [comment]
Well it just seems wrong that a 15-1 would pass, but a 100-0 would not, and it will run forever until there's a loss.

**Comment by wctgit** [comment]
I'm not sure if this is an useful suggestion, because I'm not familiar with how SPRT is calculated and whatnot, but the problem reminds me of the use of minimal knowledge prior hyperparameters in Bayesian Beta and Dirichlet probability distributions. E.g. in a Beta distribution A and B represent initial 'successes' and 'failures'. If you use A=1 and B=1, then the prior probability = 1 /  (1 + 1) = 1/2, but the distribution adapts a little slowly to new data. If you use A=0 and B=0, then the data is all important, but you can't get a valid distribution until you see at least one success and one failure. On the surface, this situation sounds very similar to what you guys are talking about with the 'wins', 'losses', and 'draws' parameters.

So, perhaps the solution for the Beta & Dirichlet distributions would help you guys for working out a compromise for these wins/losses/draws parameters.

E.g. In the Beta Distribution, the least informative prior for A and B is actually to set them both to 1/2, rather than 1 or 0. So, the prior probability of success still equals (1/2) / (1/2 + 1/2) = (1/2) / 1 = 1/2. But at the same time, since neither parameter is 0, you can still get a valid initial distribution. And since A and B are not too large, you get a more rapid convergence from new data. E.g. If you see a new success, then the updated probability becomes (1/2 + 1) / (1/2 + 1/2 + 1) = (3/2) / 2 = 3/4, instead of the slower 2/3 when you start with A=1 and B=1.

So, following the more general Dirichlet distribution, the analogous initial values for 3 parameters would be wins = 1/3, losses = 1/3, and draws  = 1/3. This would avoid the 'run forever until a loss occurs', and would probably also avoid 'falsifying the result', if my analogy with Bayesian priors is valid (which I'm not sure about). Convergence to the actual data would be very rapid. After 1 win, you would have wins = 1 + 1/3 = 4/3, losses = 1/3, and draws = 1/3. If you normalize that into a probability distribution, that would be equivalent to P(win) = (4/3) / (4/3 + 1/3 + 1/3) = (4/3)/2 = 2/3, P(loss) = (1/3)/2 = 1/6, and P(draw) = (1/3)/2 = 1/6.

Again, I don't know if my analogy is valid, but if it is, this might be a good solution/compromise.
