### ISSUE TITLE
The current match process seems bias on quick win?

### ISSUE THREAD

**Issue by earthengine** [leela-zero/leela-zero#764]
In Chinese go forum (https://tieba.baidu.com/f?ie=utf-8&kw=%E5%9B%B4%E6%A3%8B&fr=search), people observed that in many cases the winning candidates have more victories in the first half of the matches (200/400) rather than the later half.

If my understand of the match process in the server is correct, I have a theory as the following:

* The server dispatch many match games to the clients at once.
* Some games are much faster than the other (can be up to 7 times in speed of the longest one, as minimum number of steps in a game is 92 and maximum is 722, correct me if it is not the right numbers)
* The server updates the statistics when received the game results. So the sort games get counted earlier.
* As a result, a network that are good at picking up opponents's error quickly and able to avoid earlier error may show a higher winrate than it should be in the first half, as its victories are shorter. So, if a network is better in opening and fighting, but relatively bad at end game, it would appear its winrate is higher than it should be for the first half matches, but drops when the longer games finishes.

In the worst case, this might refusing some good networks that are much better at end games but make a little bit more mistakes on opening and fighting.

We may need to look at the matches database and see if we can find evidence to support the above. If it is confirmed,  my suggestion would be to send the game requests between same pair of networks in batches (10 games a batch for example). Only when all games in a batch have finished, we update the statistics to include that batch. So the statistics will be more reliable and may reduce false negatives.

The disadvantage of this is that the results will be updated slower, and it will take longer to fail a weak network. But if it really reduces false negatives, I think this is necessary.

P.S. The original idea is not mine, check 

https://www.reddit.com/r/cbaduk/comments/7t3iib/so_fast_4_new_networks_appear_in_a_day_she_use/

and find @LetterRip 's comments.

**Comment by holicst** [comment]
Good idea. Or maybe create buckets like games with 1-100, 100-200 and 200+ moves and wait until all of them have X results.

**Comment by holicst** [comment]
Another question: is it possible to train an existing network only on endgame/midgame/opening? Somehow identify and strenghten always the weakest part? Lets say our current best network mostly loses in midgame then put more resources to train it with midgame positions?

**Comment by Dorus** [comment]
But since we continue SPRT test when it goes from fail back to ongoing, we know from [all networks since we introduced SPRT test] experience that we have no networks that have been SPRT rejected but ended up over 55%.

Similar we have zero networks that got SPRT pass but then ended up below 50%. I do believe we had a random promotion at 54.xx% once or twice, but nothing bigger. In fact these networks where allowed to run a few more games and usually ended up >55%.

I do agree there is a bias in networks that score good in early game. However this is only really a problem the first 20-40 games. We once had a 10-1 network that ended up not promoting, at 11-1 it would have been SPRT pass. To prevent mistakes like that, it might be better to only start SPRT calculation after 20-30 games have been returned or so.

**Comment by holicst** [comment]
Now af4f was promoted but since promotion the win rate dropped below 47%... so I guess it was very strong in the opening but very weak in mid or endgame.

**Comment by isty2e** [comment]
In fact, the very idea was already pointed out when we started this distributed testing, though it was not taken very seriously AFAIK. I would like to see the analysis when more test matches can be accessed for this purpose.

**Comment by Dorus** [comment]
Mm, watching this latest network pass indicate the problem is worse than expected. 1) with all the early game improvements, i was expecting the nets to have peaked there, but the latest net again showed a huge increase in early game strength. 2) bias is a lot stronger, ignoring the first 20-30 games would not have been enough to prevent this 'bad' promotion.

Some heuristics like ignoring games send out in the last 20 or 30 minutes for SPRT pass/fail (but not for deciding how many games to queue). This should reduce false positives/negatives, but not increase the nr of games we send out.

**Comment by isty2e** [comment]
Oh, but one thing. Not all the match requests are not responded, and some may be terminating LZ while running matches. So I assume waiting until the batch to be fully filled is somewhat dangerous.

**Comment by Dorus** [comment]
Yeah that's exactly the reason i'm no fan of batches, but instead for a 20-30 minutes ignore timer.

**Comment by billyswong** [comment]
For heuristics I suggest delay promotion until # match results received > # unique clients (threads) assigned a match. If distinguishing threads are too hard, takes # clients * 2.

**Comment by grolich** [comment]
It doesn't seem like a huge deal, but it might have a bigger impact on efficiency/improvement speed than is immediately obvious:

Someone mentioned that it's not a big deal because @gcp wants to go the AlphaZero route, where all networks effectively auto pass (no eval). 
So what if a few networks pass without needing to? 

However, what about the other direction? 
Networks that fail because they lost fast games but have learned crucial information about weaknesses later in the game, and would pass if play kept on

In those cases, we are not only slowing the learning/improvement rate, but also, we might prevent high quality late game information from being accepted.

**Comment by Dorus** [comment]
@grolich That has already been answered a few posts above, and a number of other times as well

https://github.com/gcp/leela-zero/issues/764#issuecomment-361058357
> But since we continue SPRT test when it goes from fail back to ongoing, we know from [all networks since we introduced SPRT test] experience that we have no networks that have been SPRT rejected but ended up over 55%.

**Comment by grolich** [comment]
@Dorus , then I'm confused as to the displayed information.

Looked again at the previous statements about that. Here's my problem in understanding how it's done:

Originally, when sprt was added, @gcp agreed it was a good way to also stop failing networks from taking more match time and stopping their test matches.
Now, you say "we continue SPRT test when it goes from fail back to ongoing".

In the network list, fails maintain their low count of games, as if none of them continued, and are kept even at few dozen. When is the network given the opportunity to "go back from fail to onoing" if no further games are being made?  

So are the game numbers in the list not updated? are matches still being sent out after a fail? 

Or did you just mean you only care about cases where the games returned from the initial "failed batch" make it go back from fail to ongoing? because if so, it doesn't really say much, since often many games won't complete and also, more games would need to be sent in that case, 
and I have (perhaps through my own lack of attention, or just because I haven't seen a mention of it) yet to see an actual "fail" appear on the graph revert to ongoing. 

since obviously a network has reached a fail score and later rose slightly above the necessary wins. so in those cases, is your meaning that matches were resent? and/or updated? 
I could find no post explaining it, apologies.

**Comment by Dorus** [comment]
After a fail, already ongoing matches on the clients are not canceled. Therefore they can still submit wins and a failed net can become active again. Eventually it could even pass, but that has never happened as far as i can tell.

One exception is that a new match can be scheduled after a match has failed. If it then goes back to ongoing, the new match will take priority i think. But even then, once the new match fails it will go back to the old one. Or the new match passes, it will then continue the old one, but no longer promote it as it did not win against the current best once it does win.

**Comment by sethtroisi** [comment]
No active discussion for >1 year, with newer issue
