### ISSUE TITLE
Autogtp safe close on windows

### ISSUE THREAD

**Issue by Dorus** [leela-zero/leela-zero#914]
Right now, autogtp seems to close right away with ctrl+c keyboard command. I also believe it does this when the computer is closed down/rebooted.

The q+enter safe save+close procedure could also be used on other close events.

My C coding is more than a few years ago, so i do not have the exact code at hand, but i know it's possible. I believe windows allows programs to spend a couple seconds delaying a shutdown. See https://docs.microsoft.com/en-us/windows/console/setconsolectrlhandler

**Comment by marcocalignano** [comment]
With Ctrl-C the QProcess executing leelaz is killed even if you catch the signal and the other thread. Maybe  if leelaz manage to catch the signal too we could try to do something but it is not guaranteed.
So before you close windows, press q+Enter, like you save all your open documents.

**Comment by Dorus** [comment]
#921 reminds me that in case of crashing, we still wouldn't safe anything. What about storing every move on the disk? Possibly with a command line argument so people that are bothered with there SSD lifespan dont need to use it? You can just append every move right?

**Comment by marcocalignano** [comment]
@Dorus  I wanted to propose to print every 10th move on the screen to speed up the self playing and you want to write every move on the  you Harddrive? Each selfplay would take 10x longer than now. So to save the work done from one machine crashing you want to slow down all 600 clients? This does not make sense. If you computer crashes you can lose data with any application, that is life. Just start autogtp again., no big deal.

**Comment by Dorus** [comment]
How on earth does writing to the *console* slows down game generation? All i/o can be done async, so it should not slow down the program at all.

However i find it very hard to believe the console slows down game generation, it should take under 1 ms to write an entire game to the console. Do you have any benchmarks between a no-console-output version and is it more than 0.1% faster?

**Comment by marcocalignano** [comment]
If I do not need to write on the console I do not have to ask Leelaz the move it did, parse it and print it. And printing it involve OS sync between multiple threads. I will make a benchmark to see how much it saves I wouldn't be surprise if the improvement is a good one.

**Comment by marcocalignano** [comment]
You can make an easy test: 
`time hexdump big_file `
and 
`time hexdump big_file > /dev/null `
I did it with a 2.6 M file and goes from 726 ms to 229 ms so almost 70% in performance gain.

**Comment by Dorus** [comment]
Well 70% faster 0.1ms is still only 0.03 ms saved. See [Amdahl's law](https://en.wikipedia.org/wiki/Amdahl%27s_law).

However your remark about syncing threads has me interested. If no i/o really saves  time, we need to look into more efficient means of communicating between threads.

**Comment by marcocalignano** [comment]
But if you have 1500 ms/move on your oautgtp now and you get it 70% faster you get 450 ms/move. I think it is a pretty improvement. But anyway I will post some benchmark to see how it goes.

**Comment by Dorus** [comment]
Yes, but the majority of that 1500 ms is spend on the gpu and not on screen i/o. Only 0.1ms of it is spend on screen i/o and only 0.07ms of that is saved. On the original 1500 ms that is 0.004%.

**Comment by marcocalignano** [comment]
Yes of course that why I want to see a benchmark. But writing every move on the disk would be really deadly.

**Comment by wctgit** [comment]
For the same reasons Dorus gave, writing each move to disk would not actually be a big deal, as it can be done asynchronously, and the game moves need not wait on the disk at all (as long as you're not requiring some heavy duty ACID transaction thing that needs to be synchronized for some reason).

On the other hand, I don't really see why saving resume information to disk needs to be so precise. If you lost 10 moves due to a crash, would that really be a big problem? On my machine that would be equivalent to about 1 minute's work. On faster machines (majority), it would be even less.

If it's the case that you can tolerate some small amount of lost work, then you can use asynchronous IO buffering and writing to disk will be almost without cost (unless you're somehow generating hundreds or thousands of moves per second or something like that).

**Comment by Dorus** [comment]
@marcocalignano Any luck so far benchmarking this?

**Comment by marcocalignano** [comment]
I did some test and there is no big difference. In single thread mode there is a 10 ms gain without console output. In multi thread mode there is just 1 ms gain without Console output. I didn't get around testing with file saving because this is a bit more complicated, if you do not want to save the sgf file every move.

**Comment by sethtroisi** [comment]
closing, no active discussion for ~1 year with subsequent issues and PRs
