### ISSUE TITLE
An idea for pre-powdering on oppening for matching and playing

### ISSUE THREAD

**Issue by 2ji3150** [leela-zero/leela-zero#943]
Since we are still not using alphazero method.
For example, I saw this opening many many times on many many leela zero matching games.
https://i.imgur.com/oYNffva.png
Maybe Leela Zero think this is still the best opening.
And also, there are some same opening in other games

So I think is it an idea to let a percentage games (we can observe how many persentages were there in the matching game) and  use this fixed opening game and keep playing for matching game more faster.
And we can change this if the opening win-rate changes or other games doesn't show this kind of opening game.

And I am also curious the win-rate of white and black of this opening. If matching game just use different opening for some probability. Maybe different opening may be a all different SPRT result?  Or is it able to calculate the win-rate for the the different kinds opening games.

**Comment by WesleyDeng** [comment]
I like the idea. AI programs tend to repeat themselves in the openings. Similar openings get played over and over again (like we observe in these matches). To test fully we may need to use 'opening book' like OP suggests (This technique is used in chess AI development a lot).
However, book moves are considered 'human knowledge'. If we do use them, can we still claim the Leela Zero project is developed with ZERO human knowledge?

**Comment by wctgit** [comment]
If they are taken strictly from LZ's own 'book' of openings that it has devised in self-play, then I guess you could argue that we're just using a probabilistic cache of sorts. This wouldn't be used for training games, right? Just match games? You'd have to be pretty careful to get the probabilities right, though, IMHO. Luckily that might be easily accomplished merely through observation and data mining the match games. You could just map out the top 75-95% of openings and the other 5-25% of the time just run the opening as normal.

On the other hand, each new net will probably have a slightly different probability distribution for its opening moves, and if you're pairing 2 different nets together, it might not be obvious/easy to work out the correct joint probabilities without first observing several games, which kind of defeats the purpose. There may be a sweet-spot middle ground where you get some caching advantage while maintaining a fairly accurate probability distribution. Would require a bit of testing, IMO.

Would also require modifying AutoGTP to communicate the opening book probability distribution to the clients, and also the server should probably be the one deciding which games run a book opening, and which are free-play.

**Comment by Heiseikiseki** [comment]
Yes, that is what I am thinking.  I guess maybe that can be observed the opening in the heat map?
For example if put stone on point A then 90% would be point B. 
So I think let the server-side to generate the opening book from the current network and challenger network and send to the client is a way.   

And we can add a feature -- generate open book for Leela Zero. Not only for matching I think it may also useful for improve its time usage on real game.  And if the opening use higher playout I think it can be stronger.

**Comment by jjoshua2** [comment]
Eventually someone will use leela zero to generate a brainfish/cerebellum style opening book. It's proven to be a good method (http://www.infinitychess.com/Page/Public/Article/DefaultArticle.aspx?id=328). I would like to see how many elo that would add.

**Comment by Dorus** [comment]
This idea seems strange to me. First of all the NN is its own opening book, and self play is pretty much the perfect way to improve this internal opening book.
Second LZ is known to make strange move at very high playouts. Like early nets at 100k playouts would still play rather random moves in the center during the opening. It is not said this situation continues today, but if you want a better opening book you might as well spend that time on self play games, and use the next generation instead.
That brings me to the third point, creating an opening book is going to take an aweful lot of calculations, and it will be outdated again right away once a new net arrives.
Lastly, there are stronger bots that can create opening books, now adding a book from another bot is indeed "human knowledge", however, if you just want a stronger go bot using LZ, it would make sense to use the best possible book, and right now that wont be a book created by LZ herself.

**Comment by jjoshua2** [comment]
There is a benefit to timed games because you get extra time for the rest
of the game just by caching moves between games. Even if the nn is tuned
for 1600 Playouts so that 100k isn't as much stronger the beauty of the
cerebellum method is it can just do regular depth searches at leaf nodes of
the say million most possible openings and propogates scores up the tree.
I agree there is no use spending much time computing this until gains from
new nets get very small like when 20x256 is saturated.
But just caching moves played in self play into a book would keep oponent
from pondering and give us more time and even make playing against as a
human more enjoyable.

**Comment by Heiseikiseki** [comment]
Yes My idea is quite same as the per-cached pondering . Just make the repeated opening be calculated first and store. Just use the pre-pondering the same repeated situation. very like the human use the fuseki. Which woud be save more computation power and enjoyable.

**Comment by wctgit** [comment]
@Dorus 
> This idea seems strange to me. First of all the NN is its own opening book, and self play is pretty much the perfect way to improve this internal opening book.
As far as I'm aware, the idea was only proposed for match games (and perhaps real/non-training games), not self-play games. And as far as I'm aware, the idea was proposed mainly to speed up match games, not to improve play. That's why I described it as a probabilistic cache of openings.

I do agree with you that the 'book' or cache becomes out-of-date (obsolete is perhaps too strong) once a new net is made. However, I think it might be possible to strike a balance between getting the probabilities right and gaining a caching speed-up advantage. I'm not sure about it, though. It might not really be possible to get the probabilities adequately accurate.

Hmmm, thinking about it now, I've changed my mind. I do think it's possible to get the probabilities strongly accurate but still be able to gain caching benefit. 

The basic idea is to use a Dirichlet probability distribution to map a certain percentage of highly probable moves. First, you use the distribution strictly for recording observations. Every novel opening (up to some maximum move depth) is cached and kept a count for. After a while, you may end up with 20, 50, 100, 1000, or more openings, depending on how varied openings are (for matches, with randomness removed, hopefully this number will be fairly small). Some of those will have very high counts compared to others. I imagine the top 95% of say 40-move openings would be restricted to maybe less than 20 openings. Or somewhere around there, whatever.

Then, once the Dirichlet distribution becomes accurate enough (when used to predict each new game's opening), you can start using it to _generate_ some proportion of openings, let's say 50% of the games' openings. The other 50% are run as free play and used to keep updating the Dirichlet distribution.

Each time a new network is generated, you begin by cutting down the a0 parameter of the Dirichlet distribution by some factor, let's say 1/2 or maybe 1/10 or something. Thus, the distribution becomes more adaptive to changes in the probabilities of different openings because of the new challenger network. At first, you only observe games and update the distribution. If it becomes accurate enough again, you can finally start using it as a cache to generate some openings, while still observing some free-play openings. And again, when the SPRT test ends, and a new network is created, you slash the a0 parameter again, start observing again, eventually begin generating some openings, etc. And the process would just continue like that.

It would require testing to determine the additional parameters, such as the a0 shrinkage factor, the required-accuracy threshold, the rate-of-games-generated, max-length-of-opening, and any such other parameters. You would be trying to optimize/balance the accuracy of opening generation (probabilities) vs. time saved by caching. I think using a method like this, you could come to a reasonable compromise that would not require any taint of 'human knowledge of Go' entering any of the match SPRT evaluations. It would simply be a caching optimization for speeding up matches.

However, it would take some work, of course. The question is whether the time it saves would be worth the time invested to program it up. 

Hmm, now that I think about it a bit further, wouldn't this Dirichlet distribution I'm referring to be **very** similar to a MCTS search tree, where each observed free-play match game could simply be entered into the tree as a 'visit' or 'playout' or what-have-you? That would probably drastically reduce the effort of coding up the whole thing. You'd just have to add on the ability to measure prediction accuracy (unless that's already there); slash the a0 parameter, which would be equivalent to proportionally reducing the visit counts; pruning off unpopular branches; etc.

**Comment by wctgit** [comment]
Just to be 100% clear. I don't think any form of caching or books should be used during self-play. I think we're all agreed on that. And also, using self-play to build a book or cache would probably not be good because self-play has too much randomness involved, especially in the first 30 moves. IMO, only building a cache/book from match games or real games, played with randomness turned off, would be worthwhile.

The third point to be clear on is that generating/using a probabilistic cache to speed up match play is, I think, quite a different thing when compared to generating/using a traditional style 'opening book' to help 'pre-ponder' and thus save time during real, non-training games. This latter feature would be used to pick 'the best' move from common openings played with a variety of opponents. The former feature would be tailored only to play 'the most common' openings, and it would only be relevant to the 'champ' network, and the 'most recent challenger' network. Its purpose would not be to improve strength of play, only speed of play.

It might be possible to use the same or similar code to produce both kinds of cache/book, but when put into practice, they would have to be carefully distinguished, so that the match opening caching wouldn't end up altering the development/training of the networks.

**Comment by sethtroisi** [comment]
closing, no active discussion for ~1 year
